// Auto generated by MappingTools at 2009-11-06 09:48:34

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Interface
{
        /// <summary>
        /// 表
        /// CUSTOMS
        /// 的查询参数类	
        /// 
        /// 参数如果是数组，那么一定是array[3]，其中array[0],array[2]分别可为空，表示最小最大值，array[1]表示等于查询。
        /// 范围查询参数必须是数值型或者日期型，枚举请手动修改参数类型或代码生成中设定。
        /// 例如，需要查询一个值=2的条件，para可以设定为array[0]=array[2]=null,array[1]=2。
        /// 需要查询大于0小于50，设定为array[0]=0,array[2]=50,array[1]=null
        /// 如果同时指定，那么表示or关系，等于array[1]，或介于array[0]-array[2]之间。
        /// 三个参数可以都不填写，或只填写1个，或2个。
        /// </summary>
	[Serializable]
	public partial class Q_Customs : BaseQueryPara
	{
		private String _abbrCust;
        /// <summary>
        /// 
        /// </summary>
		public String AbbrCust
		{ get { return _abbrCust; } set { _abbrCust = value; } }

		private String _customsCode;
        /// <summary>
        /// 
        /// </summary>
		public String CustomsCode
		{ get { return _customsCode; } set { _customsCode = value; } }

		private String _customsName;
        /// <summary>
        /// 
        /// </summary>
		public String CustomsName
		{ get { return _customsName; } set { _customsName = value; } }

	}
}
