// Auto generated by MappingTools at 2009-11-06 09:48:34

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Interface
{
        /// <summary>
        /// 表
        /// JURISDICTION
        /// 的查询参数类	
        /// 口岸隶属关系
        /// 参数如果是数组，那么一定是array[3]，其中array[0],array[2]分别可为空，表示最小最大值，array[1]表示等于查询。
        /// 范围查询参数必须是数值型或者日期型，枚举请手动修改参数类型或代码生成中设定。
        /// 例如，需要查询一个值=2的条件，para可以设定为array[0]=array[2]=null,array[1]=2。
        /// 需要查询大于0小于50，设定为array[0]=0,array[2]=50,array[1]=null
        /// 如果同时指定，那么表示or关系，等于array[1]，或介于array[0]-array[2]之间。
        /// 三个参数可以都不填写，或只填写1个，或2个。
        /// </summary>
	[Serializable]
	public partial class Q_Jurisdiction : BaseQueryPara
	{
		private String _competentAuthorityId;
        /// <summary>
        /// 归口单位代码：当归口办法为1时，即相应的隶属海关代码。
        /// </summary>
		public String CompetentAuthorityId
		{ get { return _competentAuthorityId; } set { _competentAuthorityId = value; } }

		private String _portId;
        /// <summary>
        /// 口岸代码
        /// </summary>
		public String PortId
		{ get { return _portId; } set { _portId = value; } }

		private String _competencePartition;
        /// <summary>
        /// 归口办法：1-目前上海海关的海关估价管理业务的基本归口。
        /// </summary>
		public String CompetencePartition
		{ get { return _competencePartition; } set { _competencePartition = value; } }

	}
}
