// Auto generated by MappingTools at 2009-11-06 09:48:44

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Interface
{
        /// <summary>
        /// 表
        /// PLAN_TABLE
        /// 的查询参数类	
        /// 
        /// 参数如果是数组，那么一定是array[3]，其中array[0],array[2]分别可为空，表示最小最大值，array[1]表示等于查询。
        /// 范围查询参数必须是数值型或者日期型，枚举请手动修改参数类型或代码生成中设定。
        /// 例如，需要查询一个值=2的条件，para可以设定为array[0]=array[2]=null,array[1]=2。
        /// 需要查询大于0小于50，设定为array[0]=0,array[2]=50,array[1]=null
        /// 如果同时指定，那么表示or关系，等于array[1]，或介于array[0]-array[2]之间。
        /// 三个参数可以都不填写，或只填写1个，或2个。
        /// </summary>
	[Serializable]
	public partial class Q_PlanTable : BaseQueryPara
	{
		private Int32?[] _objectInstance = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] ObjectInstance
		{ get { return _objectInstance; } set { _objectInstance = value; } }

		private String _partitionStart;
        /// <summary>
        /// 
        /// </summary>
		public String PartitionStart
		{ get { return _partitionStart; } set { _partitionStart = value; } }

		private String _distribution;
        /// <summary>
        /// 
        /// </summary>
		public String Distribution
		{ get { return _distribution; } set { _distribution = value; } }

		private Int32?[] _ioCost = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] IoCost
		{ get { return _ioCost; } set { _ioCost = value; } }

		private Int32?[] _parentId = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] ParentId
		{ get { return _parentId; } set { _parentId = value; } }

		private Int32?[] _partitionId = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] PartitionId
		{ get { return _partitionId; } set { _partitionId = value; } }

		private Int32?[] _cardinality = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] Cardinality
		{ get { return _cardinality; } set { _cardinality = value; } }

		private Int32?[] _bytes = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] Bytes
		{ get { return _bytes; } set { _bytes = value; } }

		private String _options;
        /// <summary>
        /// 
        /// </summary>
		public String Options
		{ get { return _options; } set { _options = value; } }

		private DateTime?[] _timestamp = new DateTime?[3];
        /// <summary>
        /// 
        /// </summary>
		public DateTime?[] Timestamp
		{ get { return _timestamp; } set { _timestamp = value; } }

		private String _partitionStop;
        /// <summary>
        /// 
        /// </summary>
		public String PartitionStop
		{ get { return _partitionStop; } set { _partitionStop = value; } }

		private Int32?[] _searchColumns = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] SearchColumns
		{ get { return _searchColumns; } set { _searchColumns = value; } }

		private String _remarks;
        /// <summary>
        /// 
        /// </summary>
		public String Remarks
		{ get { return _remarks; } set { _remarks = value; } }

		private String _objectName;
        /// <summary>
        /// 
        /// </summary>
		public String ObjectName
		{ get { return _objectName; } set { _objectName = value; } }

		private String _objectNode;
        /// <summary>
        /// 
        /// </summary>
		public String ObjectNode
		{ get { return _objectNode; } set { _objectNode = value; } }

		private Int32?[] _tempSpace = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] TempSpace
		{ get { return _tempSpace; } set { _tempSpace = value; } }

		private Int32?[] _position = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] Position
		{ get { return _position; } set { _position = value; } }

		private String _other;
        /// <summary>
        /// 
        /// </summary>
		public String Other
		{ get { return _other; } set { _other = value; } }

		private String _objectType;
        /// <summary>
        /// 
        /// </summary>
		public String ObjectType
		{ get { return _objectType; } set { _objectType = value; } }

		private String _statementId;
        /// <summary>
        /// 
        /// </summary>
		public String StatementId
		{ get { return _statementId; } set { _statementId = value; } }

		private String _optimizer;
        /// <summary>
        /// 
        /// </summary>
		public String Optimizer
		{ get { return _optimizer; } set { _optimizer = value; } }

		private String _otherTag;
        /// <summary>
        /// 
        /// </summary>
		public String OtherTag
		{ get { return _otherTag; } set { _otherTag = value; } }

		private String _objectOwner;
        /// <summary>
        /// 
        /// </summary>
		public String ObjectOwner
		{ get { return _objectOwner; } set { _objectOwner = value; } }

		private String _operation;
        /// <summary>
        /// 
        /// </summary>
		public String Operation
		{ get { return _operation; } set { _operation = value; } }

		private Int32?[] _cost = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] Cost
		{ get { return _cost; } set { _cost = value; } }

		private Int32?[] _id = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] Id
		{ get { return _id; } set { _id = value; } }

		private Int32?[] _cpuCost = new Int32?[3];
        /// <summary>
        /// 
        /// </summary>
		public Int32?[] CpuCost
		{ get { return _cpuCost; } set { _cpuCost = value; } }

	}
}
