// Auto generated by MappingTools at 2009-11-06 09:48:45

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Interface
{
        /// <summary>
        /// 表
        /// USER_AUTH
        /// 的查询参数类	
        /// 用户授权
        /// 参数如果是数组，那么一定是array[3]，其中array[0],array[2]分别可为空，表示最小最大值，array[1]表示等于查询。
        /// 范围查询参数必须是数值型或者日期型，枚举请手动修改参数类型或代码生成中设定。
        /// 例如，需要查询一个值=2的条件，para可以设定为array[0]=array[2]=null,array[1]=2。
        /// 需要查询大于0小于50，设定为array[0]=0,array[2]=50,array[1]=null
        /// 如果同时指定，那么表示or关系，等于array[1]，或介于array[0]-array[2]之间。
        /// 三个参数可以都不填写，或只填写1个，或2个。
        /// </summary>
	[Serializable]
	public partial class Q_UserAuth : BaseQueryPara
	{
		private String _portId;
        /// <summary>
        /// 口岸代码
        /// </summary>
		public String PortId
		{ get { return _portId; } set { _portId = value; } }

		private String _opId;
        /// <summary>
        /// 用户标识
        /// </summary>
		public String OpId
		{ get { return _opId; } set { _opId = value; } }

		private String _userName;
        /// <summary>
        /// 用户名称
        /// </summary>
		public String UserName
		{ get { return _userName; } set { _userName = value; } }

		private String _active;
        /// <summary>
        /// 帐号激活否：Y-激活，N-否。
        /// </summary>
		public String Active
		{ get { return _active; } set { _active = value; } }

		private String _rank;
        /// <summary>
        /// 级别：A-主管部门；B-现场联络员；C-普通用户。
        /// </summary>
		public String Rank
		{ get { return _rank; } set { _rank = value; } }

		private String _roles;
        /// <summary>
        /// 角色代码列表
        /// </summary>
		public String Roles
		{ get { return _roles; } set { _roles = value; } }

	}
}
