// Auto generated by MappingTools at 2009-11-06 09:48:45

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Interface
{
        /// <summary>
        /// 表
        /// VERSION_CONTROL
        /// 的查询参数类	
        /// 整合数据版本控制
        /// 参数如果是数组，那么一定是array[3]，其中array[0],array[2]分别可为空，表示最小最大值，array[1]表示等于查询。
        /// 范围查询参数必须是数值型或者日期型，枚举请手动修改参数类型或代码生成中设定。
        /// 例如，需要查询一个值=2的条件，para可以设定为array[0]=array[2]=null,array[1]=2。
        /// 需要查询大于0小于50，设定为array[0]=0,array[2]=50,array[1]=null
        /// 如果同时指定，那么表示or关系，等于array[1]，或介于array[0]-array[2]之间。
        /// 三个参数可以都不填写，或只填写1个，或2个。
        /// </summary>
	[Serializable]
	public partial class Q_VersionControl : BaseQueryPara
	{
		private String _area;
        /// <summary>
        /// 地区范围：N-全国；L-本地。
        /// </summary>
		public String Area
		{ get { return _area; } set { _area = value; } }

		private Int32?[] _version = new Int32?[3];
        /// <summary>
        /// 版本：0-周期未满；非0的1位数字-周期满后的月数。
        /// </summary>
		public Int32?[] Version
		{ get { return _version; } set { _version = value; } }

		private String _periodLen;
        /// <summary>
        /// 周期长度：M-月度；Q-季度；Y-年度。
        /// </summary>
		public String PeriodLen
		{ get { return _periodLen; } set { _periodLen = value; } }

		private String _trafMode;
        /// <summary>
        /// 运输方式：全国：空格-不分运输方式；5-空运。 本地：空格。
        /// </summary>
		public String TrafMode
		{ get { return _trafMode; } set { _trafMode = value; } }

		private String _periodId;
        /// <summary>
        /// 周期标识（PIC随PERIOD_LEN：M-YYYYMM；Q-YYYYQ；Y-YYYY。）
        /// </summary>
		public String PeriodId
		{ get { return _periodId; } set { _periodId = value; } }

		private DateTime?[] _updateDate = new DateTime?[3];
        /// <summary>
        /// 更新时间
        /// </summary>
		public DateTime?[] UpdateDate
		{ get { return _updateDate; } set { _updateDate = value; } }

	}
}
