/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-03-11 15:43:25
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_AccountLog
	{
		private Int32 _id;
        /// <summary>
        /// 
        /// </summary>
		public Int32 Id
		{ get { return _id; } set { _id = value; } }

		private String _accountId;
        /// <summary>
        /// 
        /// </summary>
		public String AccountId
		{ get { return _accountId; } set { _accountId = value; } }

		private String _operater;
        /// <summary>
        /// 
        /// </summary>
		public String Operater
		{ get { return _operater; } set { _operater = value; } }

		private DateTime? _operateTime;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? OperateTime
		{ get { return _operateTime; } set { _operateTime = value; } }

		private Decimal? _amount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Amount
		{ get { return _amount; } set { _amount = value; } }

		private String _receiptId;
        /// <summary>
        /// 
        /// </summary>
		public String ReceiptId
		{ get { return _receiptId; } set { _receiptId = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "account_log";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameId = "Id";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameId = "id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAccountId = "AccountId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAccountId = "account_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOperater = "Operater";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOperater = "operater";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOperateTime = "OperateTime";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOperateTime = "operate_time";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAmount = "Amount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAmount = "amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptId = "ReceiptId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptId = "receipt_id";

        }
#endregion
	}
}
