/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-03-22 08:39:27
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ActualProfitAccounting
	{
		private Decimal? _actualProfitAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ActualProfitAmount
		{ get { return _actualProfitAmount; } set { _actualProfitAmount = value; } }

		private String _saleBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String SaleBillNo
		{ get { return _saleBillNo; } set { _saleBillNo = value; } }

		private Decimal? _extraCharges;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ExtraCharges
		{ get { return _extraCharges; } set { _extraCharges = value; } }

		private Decimal? _commission;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Commission
		{ get { return _commission; } set { _commission = value; } }

		private Boolean? _auditStatus;
        /// <summary>
        /// 
        /// </summary>
		public Boolean? AuditStatus
		{ get { return _auditStatus; } set { _auditStatus = value; } }

		private Decimal? _actualAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ActualAmount
		{ get { return _actualAmount; } set { _actualAmount = value; } }

		private Decimal? _actualPay;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ActualPay
		{ get { return _actualPay; } set { _actualPay = value; } }

		private Decimal? _returnTax;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ReturnTax
		{ get { return _returnTax; } set { _returnTax = value; } }

		private Decimal? _actualProfit;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ActualProfit
		{ get { return _actualProfit; } set { _actualProfit = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "ActualProfitAccounting";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameActualProfitAmount = "ActualProfitAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameActualProfitAmount = "actual_profit_amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleBillNo = "SaleBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleBillNo = "sale_bill_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameExtraCharges = "ExtraCharges";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameExtraCharges = "extra_charges";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCommission = "Commission";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCommission = "commission";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAuditStatus = "AuditStatus";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAuditStatus = "audit_status";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameActualAmount = "ActualAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameActualAmount = "actual_amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameActualPay = "ActualPay";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameActualPay = "actual_pay";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReturnTax = "ReturnTax";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReturnTax = "return_tax";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameActualProfit = "ActualProfit";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameActualProfit = "actual_profit";

        }
#endregion
	}
}
