/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-03-21 17:46:45
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ContractList
	{
		private Int64 _gNo;
        /// <summary>
        /// 
        /// </summary>
		public Int64 GNo
		{ get { return _gNo; } set { _gNo = value; } }

		private String _contractId;
        /// <summary>
        /// 
        /// </summary>
		public String ContractId
		{ get { return _contractId; } set { _contractId = value; } }

		private String _entryId;
        /// <summary>
        /// 
        /// </summary>
		public String EntryId
		{ get { return _entryId; } set { _entryId = value; } }

		private String _saleBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String SaleBillNo
		{ get { return _saleBillNo; } set { _saleBillNo = value; } }

		private Decimal? _invoiceTotal;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? InvoiceTotal
		{ get { return _invoiceTotal; } set { _invoiceTotal = value; } }

		private String _gUnit;
        /// <summary>
        /// 
        /// </summary>
		public String GUnit
		{ get { return _gUnit; } set { _gUnit = value; } }

		private Decimal _gQty;
        /// <summary>
        /// 
        /// </summary>
		public Decimal GQty
		{ get { return _gQty; } set { _gQty = value; } }

		private String _gName;
        /// <summary>
        /// 
        /// </summary>
		public String GName
		{ get { return _gName; } set { _gName = value; } }

		private Decimal? _invoicePrice;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? InvoicePrice
		{ get { return _invoicePrice; } set { _invoicePrice = value; } }

		private Int64 _contractNo;
        /// <summary>
        /// 
        /// </summary>
		public Int64 ContractNo
		{ get { return _contractNo; } set { _contractNo = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "contract_list";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGNo = "GNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGNo = "g_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameContractId = "ContractId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameContractId = "contract_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameEntryId = "EntryId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameEntryId = "entry_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleBillNo = "SaleBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleBillNo = "sale_bill_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInvoiceTotal = "InvoiceTotal";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInvoiceTotal = "invoice_total";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGUnit = "GUnit";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGUnit = "g_unit";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGQty = "GQty";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGQty = "g_qty";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGName = "GName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGName = "g_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInvoicePrice = "InvoicePrice";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInvoicePrice = "invoice_price";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameContractNo = "ContractNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameContractNo = "contract_no";

        }
#endregion
	}
}
