/******************************************************
* author :  chenjianwu
* email  :  chenjianwu@sh.intra.customs.gov.cn
* function: 
* Auto generated by MappingTools at 2019-06-03 16:32:08
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ContractHead
	{
		private String _xufangDailiren;
        /// <summary>
        /// 
        /// </summary>
		public String XufangDailiren
		{ get { return _xufangDailiren; } set { _xufangDailiren = value; } }

		private String _gongfangJingbanren;
        /// <summary>
        /// 
        /// </summary>
		public String GongfangJingbanren
		{ get { return _gongfangJingbanren; } set { _gongfangJingbanren = value; } }

		private String _gongfangAddress;
        /// <summary>
        /// 
        /// </summary>
		public String GongfangAddress
		{ get { return _gongfangAddress; } set { _gongfangAddress = value; } }

		private DateTime? _deliveryDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? DeliveryDate
		{ get { return _deliveryDate; } set { _deliveryDate = value; } }

		private DateTime? _gongfangQianziDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? GongfangQianziDate
		{ get { return _gongfangQianziDate; } set { _gongfangQianziDate = value; } }

		private String _gongfangFadingdaibiaoren;
        /// <summary>
        /// 
        /// </summary>
		public String GongfangFadingdaibiaoren
		{ get { return _gongfangFadingdaibiaoren; } set { _gongfangFadingdaibiaoren = value; } }

		private String _xufangTel;
        /// <summary>
        /// 
        /// </summary>
		public String XufangTel
		{ get { return _xufangTel; } set { _xufangTel = value; } }

		private String _xufangFadingdaibiaoren;
        /// <summary>
        /// 
        /// </summary>
		public String XufangFadingdaibiaoren
		{ get { return _xufangFadingdaibiaoren; } set { _xufangFadingdaibiaoren = value; } }

		private DateTime? _xufangQianziDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? XufangQianziDate
		{ get { return _xufangQianziDate; } set { _xufangQianziDate = value; } }

		private String _gongfang;
        /// <summary>
        /// 
        /// </summary>
		public String Gongfang
		{ get { return _gongfang; } set { _gongfang = value; } }

		private String _gongfangDailiren;
        /// <summary>
        /// 
        /// </summary>
		public String GongfangDailiren
		{ get { return _gongfangDailiren; } set { _gongfangDailiren = value; } }

		private String _deliveryMode;
        /// <summary>
        /// 
        /// </summary>
		public String DeliveryMode
		{ get { return _deliveryMode; } set { _deliveryMode = value; } }

		private String _xufang;
        /// <summary>
        /// 
        /// </summary>
		public String Xufang
		{ get { return _xufang; } set { _xufang = value; } }

		private String _xufangAddress;
        /// <summary>
        /// 
        /// </summary>
		public String XufangAddress
		{ get { return _xufangAddress; } set { _xufangAddress = value; } }

		private String _xufangJingbanren;
        /// <summary>
        /// 
        /// </summary>
		public String XufangJingbanren
		{ get { return _xufangJingbanren; } set { _xufangJingbanren = value; } }

		private Int32? _paymentDays;
        /// <summary>
        /// 
        /// </summary>
		public Int32? PaymentDays
		{ get { return _paymentDays; } set { _paymentDays = value; } }

		private String _contractId;
        /// <summary>
        /// 
        /// </summary>
		public String ContractId
		{ get { return _contractId; } set { _contractId = value; } }

		private String _gongfangTel;
        /// <summary>
        /// 
        /// </summary>
		public String GongfangTel
		{ get { return _gongfangTel; } set { _gongfangTel = value; } }

		private Decimal? _invoiceAll;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? InvoiceAll
		{ get { return _invoiceAll; } set { _invoiceAll = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "contract_head";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameXufangDailiren = "XufangDailiren";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameXufangDailiren = "xufang_dailiren";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGongfangJingbanren = "GongfangJingbanren";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGongfangJingbanren = "gongfang_jingbanren";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGongfangAddress = "GongfangAddress";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGongfangAddress = "gongfang_address";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDeliveryDate = "DeliveryDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDeliveryDate = "delivery_date";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGongfangQianziDate = "GongfangQianziDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGongfangQianziDate = "gongfang_qianzi_date";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGongfangFadingdaibiaoren = "GongfangFadingdaibiaoren";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGongfangFadingdaibiaoren = "gongfang_fadingdaibiaoren";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameXufangTel = "XufangTel";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameXufangTel = "xufang_tel";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameXufangFadingdaibiaoren = "XufangFadingdaibiaoren";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameXufangFadingdaibiaoren = "xufang_fadingdaibiaoren";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameXufangQianziDate = "XufangQianziDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameXufangQianziDate = "xufang_qianzi_date";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGongfang = "Gongfang";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGongfang = "gongfang";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGongfangDailiren = "GongfangDailiren";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGongfangDailiren = "gongfang_dailiren";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDeliveryMode = "DeliveryMode";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDeliveryMode = "delivery_mode";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameXufang = "Xufang";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameXufang = "xufang";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameXufangAddress = "XufangAddress";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameXufangAddress = "xufang_address";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameXufangJingbanren = "XufangJingbanren";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameXufangJingbanren = "xufang_jingbanren";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePaymentDays = "PaymentDays";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePaymentDays = "payment_days";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameContractId = "ContractId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameContractId = "contract_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGongfangTel = "GongfangTel";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGongfangTel = "gongfang_tel";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInvoiceAll = "InvoiceAll";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInvoiceAll = "invoice_all";

        }
#endregion
	}
}
