/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2019-05-31 19:26:00
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_Customers
	{
		private Int32 _id;
        /// <summary>
        /// 
        /// </summary>
		public Int32 Id
		{ get { return _id; } set { _id = value; } }

		private String _tel;
        /// <summary>
        /// 
        /// </summary>
		public String Tel
		{ get { return _tel; } set { _tel = value; } }

		private String _fadingdaibiaoren;
        /// <summary>
        /// 
        /// </summary>
		public String Fadingdaibiaoren
		{ get { return _fadingdaibiaoren; } set { _fadingdaibiaoren = value; } }

		private String _dailiren;
        /// <summary>
        /// 
        /// </summary>
		public String Dailiren
		{ get { return _dailiren; } set { _dailiren = value; } }

		private String _companyName;
        /// <summary>
        /// 
        /// </summary>
		public String CompanyName
		{ get { return _companyName; } set { _companyName = value; } }

		private String _jingban;
        /// <summary>
        /// 
        /// </summary>
		public String Jingban
		{ get { return _jingban; } set { _jingban = value; } }

		private String _address;
        /// <summary>
        /// 
        /// </summary>
		public String Address
		{ get { return _address; } set { _address = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "customers";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameId = "Id";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameId = "id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameTel = "Tel";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameTel = "tel";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFadingdaibiaoren = "Fadingdaibiaoren";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFadingdaibiaoren = "fadingdaibiaoren";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDailiren = "Dailiren";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDailiren = "dailiren";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCompanyName = "CompanyName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCompanyName = "company_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameJingban = "Jingban";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameJingban = "jingban";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAddress = "Address";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAddress = "address";

        }
#endregion
	}
}
