/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-02-07 19:54:04
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_Department
	{
		private Int32 _id;
        /// <summary>
        /// 
        /// </summary>
		public Int32 Id
		{ get { return _id; } set { _id = value; } }

		private String _code;
        /// <summary>
        /// 
        /// </summary>
		public String Code
		{ get { return _code; } set { _code = value; } }

		private String _name;
        /// <summary>
        /// 
        /// </summary>
		public String Name
		{ get { return _name; } set { _name = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "department";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameId = "Id";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameId = "id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCode = "Code";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCode = "code";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameName = "Name";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameName = "name";

        }
#endregion
	}
}
