/******************************************************
* author :  chenjianwu
* email  :  chenjianwu@sh.intra.customs.gov.cn
* function: 
* Auto generated by MappingTools at 2019-06-03 20:15:25
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_EntryList
	{
		private Int64 _gNo;
        /// <summary>
        /// 
        /// </summary>
		public Int64 GNo
		{ get { return _gNo; } set { _gNo = value; } }

		private Int32 _id;
        /// <summary>
        /// 
        /// </summary>
		public Int32 Id
		{ get { return _id; } set { _id = value; } }

		private String _agentCode;
        /// <summary>
        /// 
        /// </summary>
		public String AgentCode
		{ get { return _agentCode; } set { _agentCode = value; } }

		private DateTime? _dDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? DDate
		{ get { return _dDate; } set { _dDate = value; } }

		private Decimal? _drawbackRate;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? DrawbackRate
		{ get { return _drawbackRate; } set { _drawbackRate = value; } }

		private String _codeTs;
        /// <summary>
        /// 
        /// </summary>
		public String CodeTs
		{ get { return _codeTs; } set { _codeTs = value; } }

		private String _ownerName;
        /// <summary>
        /// 
        /// </summary>
		public String OwnerName
		{ get { return _ownerName; } set { _ownerName = value; } }

		private Boolean? _invoiceFlag;
        /// <summary>
        /// 
        /// </summary>
		public Boolean? InvoiceFlag
		{ get { return _invoiceFlag; } set { _invoiceFlag = value; } }

		private String _entryId;
        /// <summary>
        /// 
        /// </summary>
		public String EntryId
		{ get { return _entryId; } set { _entryId = value; } }

		private String _gName;
        /// <summary>
        /// 
        /// </summary>
		public String GName
		{ get { return _gName; } set { _gName = value; } }

		private Decimal? _declTotal;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? DeclTotal
		{ get { return _declTotal; } set { _declTotal = value; } }

		private DateTime? _operateTime;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? OperateTime
		{ get { return _operateTime; } set { _operateTime = value; } }

		private String _gUnit;
        /// <summary>
        /// 
        /// </summary>
		public String GUnit
		{ get { return _gUnit; } set { _gUnit = value; } }

		private String _agentName;
        /// <summary>
        /// 
        /// </summary>
		public String AgentName
		{ get { return _agentName; } set { _agentName = value; } }

		private String _operator;
        /// <summary>
        /// 
        /// </summary>
		public String Operator
		{ get { return _operator; } set { _operator = value; } }

		private Decimal? _declPrice;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? DeclPrice
		{ get { return _declPrice; } set { _declPrice = value; } }

		private Decimal? _gQty;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? GQty
		{ get { return _gQty; } set { _gQty = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "entry_list";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGNo = "GNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGNo = "g_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameId = "Id";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameId = "id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAgentCode = "AgentCode";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAgentCode = "agent_code";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDDate = "DDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDDate = "d_date";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDrawbackRate = "DrawbackRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDrawbackRate = "drawback_rate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCodeTs = "CodeTs";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCodeTs = "code_ts";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOwnerName = "OwnerName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOwnerName = "owner_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInvoiceFlag = "InvoiceFlag";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInvoiceFlag = "invoice_flag";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameEntryId = "EntryId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameEntryId = "entry_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGName = "GName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGName = "g_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDeclTotal = "DeclTotal";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDeclTotal = "decl_total";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOperateTime = "OperateTime";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOperateTime = "operate_time";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGUnit = "GUnit";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGUnit = "g_unit";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAgentName = "AgentName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAgentName = "agent_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOperator = "Operator";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOperator = "operator";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDeclPrice = "DeclPrice";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDeclPrice = "decl_price";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGQty = "GQty";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGQty = "g_qty";

        }
#endregion
	}
}
