/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-04-09 14:04:31
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_IndecreaseHead
	{
		private String _customer;
        /// <summary>
        /// 
        /// </summary>
		public String Customer
		{ get { return _customer; } set { _customer = value; } }

		private Int16? _checkStatus;
        /// <summary>
        /// 
        /// </summary>
		public Int16? CheckStatus
		{ get { return _checkStatus; } set { _checkStatus = value; } }

		private DateTime? _agentDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? AgentDate
		{ get { return _agentDate; } set { _agentDate = value; } }

		private Int32? _customerID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? CustomerID
		{ get { return _customerID; } set { _customerID = value; } }

		private Decimal? _amountAll;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? AmountAll
		{ get { return _amountAll; } set { _amountAll = value; } }

		private String _currencyID;
        /// <summary>
        /// 
        /// </summary>
		public String CurrencyID
		{ get { return _currencyID; } set { _currencyID = value; } }

		private Int32? _itemID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? ItemID
		{ get { return _itemID; } set { _itemID = value; } }

		private String _agenter;
        /// <summary>
        /// 
        /// </summary>
		public String Agenter
		{ get { return _agenter; } set { _agenter = value; } }

		private String _billNo;
        /// <summary>
        /// 
        /// </summary>
		public String BillNo
		{ get { return _billNo; } set { _billNo = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "Indecrease_head";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomer = "Customer";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomer = "customer";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCheckStatus = "CheckStatus";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCheckStatus = "check_status";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAgentDate = "AgentDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAgentDate = "agent_date";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerID = "CustomerID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerID = "customerID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAmountAll = "AmountAll";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAmountAll = "amount_all";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCurrencyID = "CurrencyID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCurrencyID = "currencyID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameItemID = "ItemID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameItemID = "itemID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAgenter = "Agenter";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAgenter = "agenter";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBillNo = "BillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBillNo = "bill_no";

        }
#endregion
	}
}
