/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-04-09 14:17:46
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_PaymentRequest
	{
		private String _empName;
        /// <summary>
        /// 
        /// </summary>
		public String EmpName
		{ get { return _empName; } set { _empName = value; } }

		private String _payeeAccountId;
        /// <summary>
        /// 
        /// </summary>
		public String PayeeAccountId
		{ get { return _payeeAccountId; } set { _payeeAccountId = value; } }

		private String _factoryBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String FactoryBillNo
		{ get { return _factoryBillNo; } set { _factoryBillNo = value; } }

		private String _deptName;
        /// <summary>
        /// 
        /// </summary>
		public String DeptName
		{ get { return _deptName; } set { _deptName = value; } }

		private String _payeeUnit;
        /// <summary>
        /// 
        /// </summary>
		public String PayeeUnit
		{ get { return _payeeUnit; } set { _payeeUnit = value; } }

		private Decimal? _amount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Amount
		{ get { return _amount; } set { _amount = value; } }

		private String _note;
        /// <summary>
        /// 
        /// </summary>
		public String Note
		{ get { return _note; } set { _note = value; } }

		private String _payeeOpeningBank;
        /// <summary>
        /// 
        /// </summary>
		public String PayeeOpeningBank
		{ get { return _payeeOpeningBank; } set { _payeeOpeningBank = value; } }

		private String _paymentId;
        /// <summary>
        /// 
        /// </summary>
		public String PaymentId
		{ get { return _paymentId; } set { _paymentId = value; } }

		private Boolean? _isUserd;
        /// <summary>
        /// 
        /// </summary>
		public Boolean? IsUserd
		{ get { return _isUserd; } set { _isUserd = value; } }

		private String _paymentExplain;
        /// <summary>
        /// 
        /// </summary>
		public String PaymentExplain
		{ get { return _paymentExplain; } set { _paymentExplain = value; } }

		private String _goodsModel;
        /// <summary>
        /// 
        /// </summary>
		public String GoodsModel
		{ get { return _goodsModel; } set { _goodsModel = value; } }

		private String _customerBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String CustomerBillNo
		{ get { return _customerBillNo; } set { _customerBillNo = value; } }

		private DateTime? _paymentDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? PaymentDate
		{ get { return _paymentDate; } set { _paymentDate = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "payment_request";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameEmpName = "EmpName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameEmpName = "emp_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePayeeAccountId = "PayeeAccountId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePayeeAccountId = "payee_account_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFactoryBillNo = "FactoryBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFactoryBillNo = "factory_bill_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDeptName = "DeptName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDeptName = "dept_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePayeeUnit = "PayeeUnit";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePayeeUnit = "payee_unit";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAmount = "Amount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAmount = "amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameNote = "Note";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameNote = "note";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePayeeOpeningBank = "PayeeOpeningBank";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePayeeOpeningBank = "payee_opening_bank";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePaymentId = "PaymentId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePaymentId = "payment_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameIsUserd = "IsUserd";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameIsUserd = "isUserd";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePaymentExplain = "PaymentExplain";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePaymentExplain = "payment_explain";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameGoodsModel = "GoodsModel";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameGoodsModel = "goods_model";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerBillNo = "CustomerBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerBillNo = "customer_bill_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePaymentDate = "PaymentDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePaymentDate = "payment_date";

        }
#endregion
	}
}
