/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-04-09 12:23:16
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_PaymentDepositHead
	{
		private String _customer;
        /// <summary>
        /// 
        /// </summary>
		public String Customer
		{ get { return _customer; } set { _customer = value; } }

		private Int16? _checkStatus;
        /// <summary>
        /// 
        /// </summary>
		public Int16? CheckStatus
		{ get { return _checkStatus; } set { _checkStatus = value; } }

		private Decimal? _unpayAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? UnpayAmountFor
		{ get { return _unpayAmountFor; } set { _unpayAmountFor = value; } }

		private DateTime? _agentDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? AgentDate
		{ get { return _agentDate; } set { _agentDate = value; } }

		private String _note;
        /// <summary>
        /// 
        /// </summary>
		public String Note
		{ get { return _note; } set { _note = value; } }

		private Boolean? _isPayed;
        /// <summary>
        /// 
        /// </summary>
		public Boolean? IsPayed
		{ get { return _isPayed; } set { _isPayed = value; } }

		private String _depositId;
        /// <summary>
        /// 
        /// </summary>
		public String DepositId
		{ get { return _depositId; } set { _depositId = value; } }

		private Decimal? _checkAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? CheckAmountFor
		{ get { return _checkAmountFor; } set { _checkAmountFor = value; } }

		private Int32? _customerID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? CustomerID
		{ get { return _customerID; } set { _customerID = value; } }

		private Decimal? _amountAll;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? AmountAll
		{ get { return _amountAll; } set { _amountAll = value; } }

		private String _currencyID;
        /// <summary>
        /// 
        /// </summary>
		public String CurrencyID
		{ get { return _currencyID; } set { _currencyID = value; } }

		private Decimal? _payAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? PayAmountFor
		{ get { return _payAmountFor; } set { _payAmountFor = value; } }

		private Int32? _itemID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? ItemID
		{ get { return _itemID; } set { _itemID = value; } }

		private String _agenter;
        /// <summary>
        /// 
        /// </summary>
		public String Agenter
		{ get { return _agenter; } set { _agenter = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "payment_deposit_head";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomer = "Customer";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomer = "customer";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCheckStatus = "CheckStatus";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCheckStatus = "check_status";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameUnpayAmountFor = "UnpayAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameUnpayAmountFor = "unpay_amount_for";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAgentDate = "AgentDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAgentDate = "agent_date";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameNote = "Note";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameNote = "note";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameIsPayed = "IsPayed";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameIsPayed = "isPayed";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDepositId = "DepositId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDepositId = "deposit_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCheckAmountFor = "CheckAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCheckAmountFor = "check_amount_for";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerID = "CustomerID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerID = "customerID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAmountAll = "AmountAll";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAmountAll = "amount_all";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCurrencyID = "CurrencyID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCurrencyID = "currencyID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePayAmountFor = "PayAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePayAmountFor = "pay_amount_for";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameItemID = "ItemID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameItemID = "itemID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAgenter = "Agenter";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAgenter = "agenter";

        }
#endregion
	}
}
