/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-04-09 14:19:40
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_PaymentReceiptList
	{
		private Decimal? _fCheckAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FCheckAmountFor
		{ get { return _fCheckAmountFor; } set { _fCheckAmountFor = value; } }

		private String _fNote;
        /// <summary>
        /// 
        /// </summary>
		public String FNote
		{ get { return _fNote; } set { _fNote = value; } }

		private Decimal? _fPurchaseAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FPurchaseAmount
		{ get { return _fPurchaseAmount; } set { _fPurchaseAmount = value; } }

		private String _receiptId;
        /// <summary>
        /// 
        /// </summary>
		public String ReceiptId
		{ get { return _receiptId; } set { _receiptId = value; } }

		private Decimal? _fPayAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FPayAmountFor
		{ get { return _fPayAmountFor; } set { _fPayAmountFor = value; } }

		private String _fBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String FBillNo
		{ get { return _fBillNo; } set { _fBillNo = value; } }

		private String _requestID;
        /// <summary>
        /// 
        /// </summary>
		public String RequestID
		{ get { return _requestID; } set { _requestID = value; } }

		private Decimal? _fUnPayAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FUnPayAmount
		{ get { return _fUnPayAmount; } set { _fUnPayAmount = value; } }

		private String _depositId;
        /// <summary>
        /// 
        /// </summary>
		public String DepositId
		{ get { return _depositId; } set { _depositId = value; } }

		private Decimal? _fUnPayAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FUnPayAmountFor
		{ get { return _fUnPayAmountFor; } set { _fUnPayAmountFor = value; } }

		private Decimal? _fPayAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FPayAmount
		{ get { return _fPayAmount; } set { _fPayAmount = value; } }

		private Int32? _fCurrencyID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FCurrencyID
		{ get { return _fCurrencyID; } set { _fCurrencyID = value; } }

		private Decimal? _fPurchaseAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FPurchaseAmountFor
		{ get { return _fPurchaseAmountFor; } set { _fPurchaseAmountFor = value; } }

		private Int32 _receiptNo;
        /// <summary>
        /// 
        /// </summary>
		public Int32 ReceiptNo
		{ get { return _receiptNo; } set { _receiptNo = value; } }

		private DateTime? _fDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? FDate
		{ get { return _fDate; } set { _fDate = value; } }

		private Int16 _fCheckStatus;
        /// <summary>
        /// 
        /// </summary>
		public Int16 FCheckStatus
		{ get { return _fCheckStatus; } set { _fCheckStatus = value; } }

		private String _indecreaseNo;
        /// <summary>
        /// 
        /// </summary>
		public String IndecreaseNo
		{ get { return _indecreaseNo; } set { _indecreaseNo = value; } }

		private Decimal? _fCheckAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FCheckAmount
		{ get { return _fCheckAmount; } set { _fCheckAmount = value; } }

		private Double? _fExchangeRate;
        /// <summary>
        /// 
        /// </summary>
		public Double? FExchangeRate
		{ get { return _fExchangeRate; } set { _fExchangeRate = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "payment_receipt_list";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCheckAmountFor = "FCheckAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCheckAmountFor = "FCheckAmountFor";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFNote = "FNote";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFNote = "FNote";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFPurchaseAmount = "FPurchaseAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFPurchaseAmount = "FPurchaseAmount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptId = "ReceiptId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptId = "receipt_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFPayAmountFor = "FPayAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFPayAmountFor = "FPayAmountFor";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFBillNo = "FBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFBillNo = "FBillNo";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameRequestID = "RequestID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameRequestID = "RequestID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFUnPayAmount = "FUnPayAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFUnPayAmount = "FUnPayAmount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDepositId = "DepositId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDepositId = "Deposit_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFUnPayAmountFor = "FUnPayAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFUnPayAmountFor = "FUnPayAmountFor";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFPayAmount = "FPayAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFPayAmount = "FPayAmount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCurrencyID = "FCurrencyID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCurrencyID = "FCurrencyID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFPurchaseAmountFor = "FPurchaseAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFPurchaseAmountFor = "FPurchaseAmountFor";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptNo = "ReceiptNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptNo = "receipt_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFDate = "FDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFDate = "FDate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCheckStatus = "FCheckStatus";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCheckStatus = "FCheckStatus";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameIndecreaseNo = "IndecreaseNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameIndecreaseNo = "InDecrease_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCheckAmount = "FCheckAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCheckAmount = "FCheckAmount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFExchangeRate = "FExchangeRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFExchangeRate = "FExchangeRate";

        }
#endregion
	}
}
