/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-04-08 10:12:48
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ProfitAccountingList
	{
		private Decimal? _saleQty;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? SaleQty
		{ get { return _saleQty; } set { _saleQty = value; } }

		private Decimal? _accessoryPrice;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? AccessoryPrice
		{ get { return _accessoryPrice; } set { _accessoryPrice = value; } }

		private Decimal? _buyPrice;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? BuyPrice
		{ get { return _buyPrice; } set { _buyPrice = value; } }

		private Decimal? _profit;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Profit
		{ get { return _profit; } set { _profit = value; } }

		private Boolean? _saleRate;
        /// <summary>
        /// 
        /// </summary>
		public Boolean? SaleRate
		{ get { return _saleRate; } set { _saleRate = value; } }

		private Boolean? _buyRate;
        /// <summary>
        /// 
        /// </summary>
		public Boolean? BuyRate
		{ get { return _buyRate; } set { _buyRate = value; } }

		private String _buyBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String BuyBillNo
		{ get { return _buyBillNo; } set { _buyBillNo = value; } }

		private Decimal? _salePrice;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? SalePrice
		{ get { return _salePrice; } set { _salePrice = value; } }

		private Decimal? _exchangeRate;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ExchangeRate
		{ get { return _exchangeRate; } set { _exchangeRate = value; } }

		private Int32? _empId;
        /// <summary>
        /// 
        /// </summary>
		public Int32? EmpId
		{ get { return _empId; } set { _empId = value; } }

		private Int32 _fInterID;
        /// <summary>
        /// 
        /// </summary>
		public Int32 FInterID
		{ get { return _fInterID; } set { _fInterID = value; } }

		private Decimal? _length;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Length
		{ get { return _length; } set { _length = value; } }

		private Decimal? _returnRate;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ReturnRate
		{ get { return _returnRate; } set { _returnRate = value; } }

		private Decimal? _volume;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Volume
		{ get { return _volume; } set { _volume = value; } }

		private String _currency;
        /// <summary>
        /// 
        /// </summary>
		public String Currency
		{ get { return _currency; } set { _currency = value; } }

		private Decimal? _commission;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Commission
		{ get { return _commission; } set { _commission = value; } }

		private Int32? _deptId;
        /// <summary>
        /// 
        /// </summary>
		public Int32? DeptId
		{ get { return _deptId; } set { _deptId = value; } }

		private Decimal? _capacity;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Capacity
		{ get { return _capacity; } set { _capacity = value; } }

		private String _accessory;
        /// <summary>
        /// 
        /// </summary>
		public String Accessory
		{ get { return _accessory; } set { _accessory = value; } }

		private String _fName;
        /// <summary>
        /// 
        /// </summary>
		public String FName
		{ get { return _fName; } set { _fName = value; } }

		private String _fNumber;
        /// <summary>
        /// 
        /// </summary>
		public String FNumber
		{ get { return _fNumber; } set { _fNumber = value; } }

		private String _saleBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String SaleBillNo
		{ get { return _saleBillNo; } set { _saleBillNo = value; } }

		private Decimal? _taxRate;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? TaxRate
		{ get { return _taxRate; } set { _taxRate = value; } }

		private Decimal? _height;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Height
		{ get { return _height; } set { _height = value; } }

		private Decimal? _width;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Width
		{ get { return _width; } set { _width = value; } }

		private Decimal? _estimateFreightCharge;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? EstimateFreightCharge
		{ get { return _estimateFreightCharge; } set { _estimateFreightCharge = value; } }

		private Int32 _buyFentryid;
        /// <summary>
        /// 
        /// </summary>
		public Int32 BuyFentryid
		{ get { return _buyFentryid; } set { _buyFentryid = value; } }

		private String _sEOrderID;
        /// <summary>
        /// 
        /// </summary>
		public String SEOrderID
		{ get { return _sEOrderID; } set { _sEOrderID = value; } }

		private Decimal? _buyQty;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? BuyQty
		{ get { return _buyQty; } set { _buyQty = value; } }

		private Int32 _fItemID;
        /// <summary>
        /// 
        /// </summary>
		public Int32 FItemID
		{ get { return _fItemID; } set { _fItemID = value; } }

		private Int32 _saleFentryid;
        /// <summary>
        /// 
        /// </summary>
		public Int32 SaleFentryid
		{ get { return _saleFentryid; } set { _saleFentryid = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "ProfitAccountingList";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleQty = "SaleQty";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleQty = "sale_qty";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAccessoryPrice = "AccessoryPrice";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAccessoryPrice = "accessory_price";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBuyPrice = "BuyPrice";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBuyPrice = "buy_price";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameProfit = "Profit";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameProfit = "profit";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleRate = "SaleRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleRate = "sale_rate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBuyRate = "BuyRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBuyRate = "buy_rate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBuyBillNo = "BuyBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBuyBillNo = "buy_bill_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSalePrice = "SalePrice";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSalePrice = "sale_price";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameExchangeRate = "ExchangeRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameExchangeRate = "exchange_rate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameEmpId = "EmpId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameEmpId = "emp_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFInterID = "FInterID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFInterID = "FInterID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameLength = "Length";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameLength = "length";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReturnRate = "ReturnRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReturnRate = "return_rate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameVolume = "Volume";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameVolume = "volume";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCurrency = "Currency";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCurrency = "currency";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCommission = "Commission";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCommission = "commission";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDeptId = "DeptId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDeptId = "dept_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCapacity = "Capacity";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCapacity = "capacity";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAccessory = "Accessory";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAccessory = "accessory";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFName = "FName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFName = "FName";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFNumber = "FNumber";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFNumber = "FNumber";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleBillNo = "SaleBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleBillNo = "sale_bill_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameTaxRate = "TaxRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameTaxRate = "tax_rate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameHeight = "Height";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameHeight = "height";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameWidth = "Width";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameWidth = "width";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameEstimateFreightCharge = "EstimateFreightCharge";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameEstimateFreightCharge = "estimate_freight_charge";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBuyFentryid = "BuyFentryid";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBuyFentryid = "Buy_FEntryID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSEOrderID = "SEOrderID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSEOrderID = "SEOrderID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBuyQty = "BuyQty";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBuyQty = "buy_qty";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFItemID = "FItemID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFItemID = "FItemID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleFentryid = "SaleFentryid";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleFentryid = "Sale_FEntryID";

        }
#endregion
	}
}
