/******************************************************
* author :  chenjianwu
* email  :  chenjianwu@sh.intra.customs.gov.cn
* function: 
* Auto generated by MappingTools at 2020-02-06 13:40:35
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ProfitBudgetList
	{
		private Int32 _buyFentryid;
        /// <summary>
        /// 
        /// </summary>
		public Int32 BuyFentryid
		{ get { return _buyFentryid; } set { _buyFentryid = value; } }

		private Int32 _fItemID;
        /// <summary>
        /// 
        /// </summary>
		public Int32 FItemID
		{ get { return _fItemID; } set { _fItemID = value; } }

		private Decimal? _profit;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Profit
		{ get { return _profit; } set { _profit = value; } }

		private String _saleBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String SaleBillNo
		{ get { return _saleBillNo; } set { _saleBillNo = value; } }

		private Int32? _deptId;
        /// <summary>
        /// 
        /// </summary>
		public Int32? DeptId
		{ get { return _deptId; } set { _deptId = value; } }

		private String _accessory;
        /// <summary>
        /// 
        /// </summary>
		public String Accessory
		{ get { return _accessory; } set { _accessory = value; } }

		private Decimal? _saleQty;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? SaleQty
		{ get { return _saleQty; } set { _saleQty = value; } }

		private Int32 _saleFentryid;
        /// <summary>
        /// 
        /// </summary>
		public Int32 SaleFentryid
		{ get { return _saleFentryid; } set { _saleFentryid = value; } }

		private Decimal? _buyQty;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? BuyQty
		{ get { return _buyQty; } set { _buyQty = value; } }

		private Decimal? _accessoryPrice;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? AccessoryPrice
		{ get { return _accessoryPrice; } set { _accessoryPrice = value; } }

		private Int32? _empId;
        /// <summary>
        /// 
        /// </summary>
		public Int32? EmpId
		{ get { return _empId; } set { _empId = value; } }

		private Decimal? _salePrice;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? SalePrice
		{ get { return _salePrice; } set { _salePrice = value; } }

		private Int32 _fInterID;
        /// <summary>
        /// 
        /// </summary>
		public Int32 FInterID
		{ get { return _fInterID; } set { _fInterID = value; } }

		private String _buyBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String BuyBillNo
		{ get { return _buyBillNo; } set { _buyBillNo = value; } }

		private Decimal? _buyPrice;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? BuyPrice
		{ get { return _buyPrice; } set { _buyPrice = value; } }

		private Decimal? _exchangeRate;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ExchangeRate
		{ get { return _exchangeRate; } set { _exchangeRate = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "ProfitBudgetList";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBuyFentryid = "BuyFentryid";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBuyFentryid = "Buy_FEntryID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFItemID = "FItemID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFItemID = "FItemID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameProfit = "Profit";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameProfit = "profit";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleBillNo = "SaleBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleBillNo = "sale_bill_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDeptId = "DeptId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDeptId = "dept_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAccessory = "Accessory";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAccessory = "accessory";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleQty = "SaleQty";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleQty = "sale_qty";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleFentryid = "SaleFentryid";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleFentryid = "Sale_FEntryID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBuyQty = "BuyQty";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBuyQty = "buy_qty";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAccessoryPrice = "AccessoryPrice";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAccessoryPrice = "accessory_price";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameEmpId = "EmpId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameEmpId = "emp_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSalePrice = "SalePrice";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSalePrice = "sale_price";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFInterID = "FInterID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFInterID = "FInterID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBuyBillNo = "BuyBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBuyBillNo = "buy_bill_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBuyPrice = "BuyPrice";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBuyPrice = "buy_price";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameExchangeRate = "ExchangeRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameExchangeRate = "exchange_rate";

        }
#endregion
	}
}
