/******************************************************
* author :  chenjianwu
* email  :  chenjianwu@sh.intra.customs.gov.cn
* function: 
* Auto generated by MappingTools at 2020-02-09 09:15:09
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ProfitBudget
	{
		private Boolean? _auditState;
        /// <summary>
        /// 0:未审核|1：审核
        /// </summary>
		public Boolean? AuditState
		{ get { return _auditState; } set { _auditState = value; } }

		private Decimal? _extraCharges;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ExtraCharges
		{ get { return _extraCharges; } set { _extraCharges = value; } }

		private DateTime? _updateTime;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? UpdateTime
		{ get { return _updateTime; } set { _updateTime = value; } }

		private Int32 _fInterID;
        /// <summary>
        /// 
        /// </summary>
		public Int32 FInterID
		{ get { return _fInterID; } set { _fInterID = value; } }

		private String _saleBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String SaleBillNo
		{ get { return _saleBillNo; } set { _saleBillNo = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "ProfitBudget";
        /// <summary>
        /// 属性名称定义 0
        /// </summary>
public const string PropertyNameAuditState = "AuditState";
        /// <summary>
        /// 字段名称定义 0
        /// </summary>
public const string FieldNameAuditState = "audit_state";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameExtraCharges = "ExtraCharges";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameExtraCharges = "extra_charges";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameUpdateTime = "UpdateTime";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameUpdateTime = "update_time";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFInterID = "FInterID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFInterID = "FInterID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSaleBillNo = "SaleBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSaleBillNo = "sale_bill_no";

        }
#endregion
	}
}
