/******************************************************
* author :  chenjianwu
* email  :  chenjianwu@sh.intra.customs.gov.cn
* function: 
* Auto generated by MappingTools at 2020-02-24 14:58:03
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ReceiptHead
	{
		private String _receiptType;
        /// <summary>
        /// 
        /// </summary>
		public String ReceiptType
		{ get { return _receiptType; } set { _receiptType = value; } }

		private Int32? _fPreparer;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FPreparer
		{ get { return _fPreparer; } set { _fPreparer = value; } }

		private String _currency;
        /// <summary>
        /// 
        /// </summary>
		public String Currency
		{ get { return _currency; } set { _currency = value; } }

		private Int32? _fDeptID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FDeptID
		{ get { return _fDeptID; } set { _fDeptID = value; } }

		private DateTime? _receiptDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? ReceiptDate
		{ get { return _receiptDate; } set { _receiptDate = value; } }

		private Decimal? _receiptCharge;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ReceiptCharge
		{ get { return _receiptCharge; } set { _receiptCharge = value; } }

		private Int32? _fCheckStatus;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FCheckStatus
		{ get { return _fCheckStatus; } set { _fCheckStatus = value; } }

		private Decimal? _amount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Amount
		{ get { return _amount; } set { _amount = value; } }

		private Int32? _fChecker;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FChecker
		{ get { return _fChecker; } set { _fChecker = value; } }

		private String _receiptId;
        /// <summary>
        /// 
        /// </summary>
		public String ReceiptId
		{ get { return _receiptId; } set { _receiptId = value; } }

		private String _customerCode;
        /// <summary>
        /// 
        /// </summary>
		public String CustomerCode
		{ get { return _customerCode; } set { _customerCode = value; } }

		private String _customerName;
        /// <summary>
        /// 
        /// </summary>
		public String CustomerName
		{ get { return _customerName; } set { _customerName = value; } }

		private String _note;
        /// <summary>
        /// 
        /// </summary>
		public String Note
		{ get { return _note; } set { _note = value; } }

		private DateTime? _fCheckDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? FCheckDate
		{ get { return _fCheckDate; } set { _fCheckDate = value; } }

		private Int32? _fEmpID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FEmpID
		{ get { return _fEmpID; } set { _fEmpID = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "receipt_head";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptType = "ReceiptType";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptType = "receipt_type";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFPreparer = "FPreparer";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFPreparer = "FPreparer";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCurrency = "Currency";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCurrency = "currency";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFDeptID = "FDeptID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFDeptID = "FDeptID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptDate = "ReceiptDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptDate = "receipt_date";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptCharge = "ReceiptCharge";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptCharge = "receipt_charge";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCheckStatus = "FCheckStatus";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCheckStatus = "FCheckStatus";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAmount = "Amount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAmount = "amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFChecker = "FChecker";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFChecker = "FChecker";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptId = "ReceiptId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptId = "receipt_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerCode = "CustomerCode";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerCode = "customer_code";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerName = "CustomerName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerName = "customer_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameNote = "Note";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameNote = "note";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCheckDate = "FCheckDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCheckDate = "FCheckDate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFEmpID = "FEmpID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFEmpID = "FEmpID";

        }
#endregion
	}
}
