/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-03-11 14:49:25
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ReceiptHead
	{
		private Int32? _fCheckStatus;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FCheckStatus
		{ get { return _fCheckStatus; } set { _fCheckStatus = value; } }

		private String _receiptId;
        /// <summary>
        /// 
        /// </summary>
		public String ReceiptId
		{ get { return _receiptId; } set { _receiptId = value; } }

		private String _note;
        /// <summary>
        /// 
        /// </summary>
		public String Note
		{ get { return _note; } set { _note = value; } }

		private Int32? _fChecker;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FChecker
		{ get { return _fChecker; } set { _fChecker = value; } }

		private DateTime? _receiptDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? ReceiptDate
		{ get { return _receiptDate; } set { _receiptDate = value; } }

		private Int32? _fPreparer;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FPreparer
		{ get { return _fPreparer; } set { _fPreparer = value; } }

		private String _currency;
        /// <summary>
        /// 
        /// </summary>
		public String Currency
		{ get { return _currency; } set { _currency = value; } }

		private Int32? _fDeptID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FDeptID
		{ get { return _fDeptID; } set { _fDeptID = value; } }

		private Int32? _fEmpID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FEmpID
		{ get { return _fEmpID; } set { _fEmpID = value; } }

		private String _receiptType;
        /// <summary>
        /// 
        /// </summary>
		public String ReceiptType
		{ get { return _receiptType; } set { _receiptType = value; } }

		private String _accountId;
        /// <summary>
        /// 
        /// </summary>
		public String AccountId
		{ get { return _accountId; } set { _accountId = value; } }

		private Decimal? _amount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Amount
		{ get { return _amount; } set { _amount = value; } }

		private DateTime? _fCheckDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? FCheckDate
		{ get { return _fCheckDate; } set { _fCheckDate = value; } }

		private String _customerName;
        /// <summary>
        /// 
        /// </summary>
		public String CustomerName
		{ get { return _customerName; } set { _customerName = value; } }

		private String _customerCode;
        /// <summary>
        /// 
        /// </summary>
		public String CustomerCode
		{ get { return _customerCode; } set { _customerCode = value; } }

		private Int32? _auditStatus;
        /// <summary>
        /// 0:未提交审核；1：提交审核；2：审核不通过；3：审核通过
        /// </summary>
		public Int32? AuditStatus
		{ get { return _auditStatus; } set { _auditStatus = value; } }

		private Decimal? _receiptCharge;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ReceiptCharge
		{ get { return _receiptCharge; } set { _receiptCharge = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "receipt_head";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCheckStatus = "FCheckStatus";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCheckStatus = "FCheckStatus";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptId = "ReceiptId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptId = "receipt_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameNote = "Note";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameNote = "note";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFChecker = "FChecker";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFChecker = "FChecker";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptDate = "ReceiptDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptDate = "receipt_date";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFPreparer = "FPreparer";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFPreparer = "FPreparer";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCurrency = "Currency";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCurrency = "currency";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFDeptID = "FDeptID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFDeptID = "FDeptID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFEmpID = "FEmpID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFEmpID = "FEmpID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptType = "ReceiptType";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptType = "receipt_type";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAccountId = "AccountId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAccountId = "account_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAmount = "Amount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAmount = "amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCheckDate = "FCheckDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCheckDate = "FCheckDate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerName = "CustomerName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerName = "customer_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerCode = "CustomerCode";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerCode = "customer_code";
        /// <summary>
        /// 属性名称定义 0
        /// </summary>
public const string PropertyNameAuditStatus = "AuditStatus";
        /// <summary>
        /// 字段名称定义 0
        /// </summary>
public const string FieldNameAuditStatus = "audit_status";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptCharge = "ReceiptCharge";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptCharge = "receipt_charge";

        }
#endregion
	}
}
