/******************************************************
* author :  chenjianwu
* email  :  chenjianwu@sh.intra.customs.gov.cn
* function: 
* Auto generated by MappingTools at 2020-02-14 15:16:16
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ReceiptList
	{
		private Decimal? _fReceiveAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FReceiveAmount
		{ get { return _fReceiveAmount; } set { _fReceiveAmount = value; } }

		private Decimal? _fInvoiceAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FInvoiceAmount
		{ get { return _fInvoiceAmount; } set { _fInvoiceAmount = value; } }

		private String _fNote;
        /// <summary>
        /// 
        /// </summary>
		public String FNote
		{ get { return _fNote; } set { _fNote = value; } }

		private Int16 _fCheckStatus;
        /// <summary>
        /// 
        /// </summary>
		public Int16 FCheckStatus
		{ get { return _fCheckStatus; } set { _fCheckStatus = value; } }

		private String _receiptId;
        /// <summary>
        /// 
        /// </summary>
		public String ReceiptId
		{ get { return _receiptId; } set { _receiptId = value; } }

		private String _fCurrency;
        /// <summary>
        /// 
        /// </summary>
		public String FCurrency
		{ get { return _fCurrency; } set { _fCurrency = value; } }

		private Decimal? _fInvoiceAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FInvoiceAmountFor
		{ get { return _fInvoiceAmountFor; } set { _fInvoiceAmountFor = value; } }

		private Decimal? _fUnReceiveAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FUnReceiveAmount
		{ get { return _fUnReceiveAmount; } set { _fUnReceiveAmount = value; } }

		private Int32? _fChecker;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FChecker
		{ get { return _fChecker; } set { _fChecker = value; } }

		private Decimal? _fReceiveAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FReceiveAmountFor
		{ get { return _fReceiveAmountFor; } set { _fReceiveAmountFor = value; } }

		private Int32? _fPreparer;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FPreparer
		{ get { return _fPreparer; } set { _fPreparer = value; } }

		private String _fBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String FBillNo
		{ get { return _fBillNo; } set { _fBillNo = value; } }

		private Int32? _fDeptID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FDeptID
		{ get { return _fDeptID; } set { _fDeptID = value; } }

		private Int32? _fEmpID;
        /// <summary>
        /// 
        /// </summary>
		public Int32? FEmpID
		{ get { return _fEmpID; } set { _fEmpID = value; } }

		private Decimal? _fUnReceiveAmountFor;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? FUnReceiveAmountFor
		{ get { return _fUnReceiveAmountFor; } set { _fUnReceiveAmountFor = value; } }

		private Int32 _receiptNo;
        /// <summary>
        /// 
        /// </summary>
		public Int32 ReceiptNo
		{ get { return _receiptNo; } set { _receiptNo = value; } }

		private DateTime? _fDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? FDate
		{ get { return _fDate; } set { _fDate = value; } }

		private DateTime? _fCheckDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? FCheckDate
		{ get { return _fCheckDate; } set { _fCheckDate = value; } }

		private Double? _fExchangeRate;
        /// <summary>
        /// 
        /// </summary>
		public Double? FExchangeRate
		{ get { return _fExchangeRate; } set { _fExchangeRate = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "receipt_list";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFReceiveAmount = "FReceiveAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFReceiveAmount = "FReceiveAmount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFInvoiceAmount = "FInvoiceAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFInvoiceAmount = "FInvoiceAmount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFNote = "FNote";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFNote = "FNote";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCheckStatus = "FCheckStatus";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCheckStatus = "FCheckStatus";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptId = "ReceiptId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptId = "receipt_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCurrency = "FCurrency";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCurrency = "FCurrency";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFInvoiceAmountFor = "FInvoiceAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFInvoiceAmountFor = "FInvoiceAmountFor";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFUnReceiveAmount = "FUnReceiveAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFUnReceiveAmount = "FUnReceiveAmount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFChecker = "FChecker";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFChecker = "FChecker";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFReceiveAmountFor = "FReceiveAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFReceiveAmountFor = "FReceiveAmountFor";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFPreparer = "FPreparer";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFPreparer = "FPreparer";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFBillNo = "FBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFBillNo = "FBillNo";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFDeptID = "FDeptID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFDeptID = "FDeptID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFEmpID = "FEmpID";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFEmpID = "FEmpID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFUnReceiveAmountFor = "FUnReceiveAmountFor";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFUnReceiveAmountFor = "FUnReceiveAmountFor";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptNo = "ReceiptNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptNo = "receipt_no";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFDate = "FDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFDate = "FDate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFCheckDate = "FCheckDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFCheckDate = "FCheckDate";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFExchangeRate = "FExchangeRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFExchangeRate = "FExchangeRate";

        }
#endregion
	}
}
