/******************************************************
* author :  chenjianwu
* email  :  chenjianwu@sh.intra.customs.gov.cn
* function: 
* Auto generated by MappingTools at 2020-02-14 15:16:16
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_ReceiptHead
	{
		private Decimal? _amount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? Amount
		{ get { return _amount; } set { _amount = value; } }

		private Decimal? _receiptCharge;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ReceiptCharge
		{ get { return _receiptCharge; } set { _receiptCharge = value; } }

		private String _customerName;
        /// <summary>
        /// 
        /// </summary>
		public String CustomerName
		{ get { return _customerName; } set { _customerName = value; } }

		private String _customerCode;
        /// <summary>
        /// 
        /// </summary>
		public String CustomerCode
		{ get { return _customerCode; } set { _customerCode = value; } }

		private String _currency;
        /// <summary>
        /// 
        /// </summary>
		public String Currency
		{ get { return _currency; } set { _currency = value; } }

		private DateTime? _receiptDate;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? ReceiptDate
		{ get { return _receiptDate; } set { _receiptDate = value; } }

		private String _receiptId;
        /// <summary>
        /// 
        /// </summary>
		public String ReceiptId
		{ get { return _receiptId; } set { _receiptId = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "receipt_head";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAmount = "Amount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAmount = "amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptCharge = "ReceiptCharge";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptCharge = "receipt_charge";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerName = "CustomerName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerName = "customer_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerCode = "CustomerCode";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerCode = "customer_code";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCurrency = "Currency";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCurrency = "currency";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptDate = "ReceiptDate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptDate = "receipt_date";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameReceiptId = "ReceiptId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameReceiptId = "receipt_id";

        }
#endregion
	}
}
