/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-03-10 21:37:32
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_SettlementLog
	{
		private String _outOpeningBank;
        /// <summary>
        /// 
        /// </summary>
		public String OutOpeningBank
		{ get { return _outOpeningBank; } set { _outOpeningBank = value; } }

		private Decimal? _inAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? InAmount
		{ get { return _inAmount; } set { _inAmount = value; } }

		private String _outAccountId;
        /// <summary>
        /// 
        /// </summary>
		public String OutAccountId
		{ get { return _outAccountId; } set { _outAccountId = value; } }

		private String _inAccountId;
        /// <summary>
        /// 
        /// </summary>
		public String InAccountId
		{ get { return _inAccountId; } set { _inAccountId = value; } }

		private Decimal? _outAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? OutAmount
		{ get { return _outAmount; } set { _outAmount = value; } }

		private Int32 _id;
        /// <summary>
        /// 
        /// </summary>
		public Int32 Id
		{ get { return _id; } set { _id = value; } }

		private Decimal? _inSettlementAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? InSettlementAmount
		{ get { return _inSettlementAmount; } set { _inSettlementAmount = value; } }

		private Int32? _inCurrencyid;
        /// <summary>
        /// 
        /// </summary>
		public Int32? InCurrencyid
		{ get { return _inCurrencyid; } set { _inCurrencyid = value; } }

		private String _operater;
        /// <summary>
        /// 
        /// </summary>
		public String Operater
		{ get { return _operater; } set { _operater = value; } }

		private String _outAccountName;
        /// <summary>
        /// 
        /// </summary>
		public String OutAccountName
		{ get { return _outAccountName; } set { _outAccountName = value; } }

		private String _inOpeningBank;
        /// <summary>
        /// 
        /// </summary>
		public String InOpeningBank
		{ get { return _inOpeningBank; } set { _inOpeningBank = value; } }

		private Int32? _outCurrencyid;
        /// <summary>
        /// 
        /// </summary>
		public Int32? OutCurrencyid
		{ get { return _outCurrencyid; } set { _outCurrencyid = value; } }

		private DateTime? _operateTime;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? OperateTime
		{ get { return _operateTime; } set { _operateTime = value; } }

		private String _inAccountName;
        /// <summary>
        /// 
        /// </summary>
		public String InAccountName
		{ get { return _inAccountName; } set { _inAccountName = value; } }

		private Decimal? _outSettlementAmount;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? OutSettlementAmount
		{ get { return _outSettlementAmount; } set { _outSettlementAmount = value; } }

		private Decimal? _exchangeRate;
        /// <summary>
        /// 
        /// </summary>
		public Decimal? ExchangeRate
		{ get { return _exchangeRate; } set { _exchangeRate = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "settlement_log";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOutOpeningBank = "OutOpeningBank";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOutOpeningBank = "out_opening_bank";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInAmount = "InAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInAmount = "in_amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOutAccountId = "OutAccountId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOutAccountId = "out_account_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInAccountId = "InAccountId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInAccountId = "in_account_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOutAmount = "OutAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOutAmount = "out_amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameId = "Id";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameId = "id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInSettlementAmount = "InSettlementAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInSettlementAmount = "in_settlement_amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInCurrencyid = "InCurrencyid";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInCurrencyid = "in_currencyID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOperater = "Operater";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOperater = "operater";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOutAccountName = "OutAccountName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOutAccountName = "out_account_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInOpeningBank = "InOpeningBank";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInOpeningBank = "in_opening_bank";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOutCurrencyid = "OutCurrencyid";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOutCurrencyid = "out_currencyID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOperateTime = "OperateTime";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOperateTime = "operate_time";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInAccountName = "InAccountName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInAccountName = "in_account_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOutSettlementAmount = "OutSettlementAmount";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOutSettlementAmount = "out_settlement_amount";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameExchangeRate = "ExchangeRate";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameExchangeRate = "exchange_rate";

        }
#endregion
	}
}
