/******************************************************
* author :  西門飄雪
* email  :  西門飄雪
* function: 
* Auto generated by MappingTools at 2020-03-05 19:52:40
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_SEOrderNODone
	{
		

		private String _depositId;
        /// <summary>
        /// 
        /// </summary>
		public String DepositId
		{ get { return _depositId; } set { _depositId = value; } }

		private String _customerCode;
        /// <summary>
        /// 
        /// </summary>
		public String CustomerCode
		{ get { return _customerCode; } set { _customerCode = value; } }

		private String _fBillNo;
        /// <summary>
        /// 
        /// </summary>
		public String FBillNo
		{ get { return _fBillNo; } set { _fBillNo = value; } }

		private String _customerName;
        /// <summary>
        /// 
        /// </summary>
		public String CustomerName
		{ get { return _customerName; } set { _customerName = value; } }

		private DateTime? _insertTime;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? InsertTime
		{ get { return _insertTime; } set { _insertTime = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "SEOrderNODone";
       
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDepositId = "DepositId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDepositId = "deposit_id";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerCode = "CustomerCode";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerCode = "customer_code";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameFBillNo = "FBillNo";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameFBillNo = "FBillNo";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomerName = "CustomerName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomerName = "customer_name";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameInsertTime = "InsertTime";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameInsertTime = "insert_time";

        }
#endregion
	}
}
