// Auto generated by MappingTools at 2010-03-29 11:59:13

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Entity
{
        /// <summary>
        /// 调整绩效记录
        /// </summary>
	public partial class T_AdjustmentPerform
	{
		private Decimal? _tradeTotalOld;
        /// <summary>
        /// 系统提供原成交总价
        /// </summary>
		public Decimal? TradeTotalOld
		{ get { return _tradeTotalOld; } set { _tradeTotalOld = value; } }

		private Decimal? _newCPriceLevelPlus;
        /// <summary>
        /// 拟改成税号加入被调整商品项后的口岸价格水平
        /// </summary>
		public Decimal? NewCPriceLevelPlus
		{ get { return _newCPriceLevelPlus; } set { _newCPriceLevelPlus = value; } }

		private Decimal? _oldCDef2expectedMinus;
        /// <summary>
        /// 原税号剔除被调整商品项后的口岸理论税差
        /// </summary>
		public Decimal? OldCDef2expectedMinus
		{ get { return _oldCDef2expectedMinus; } set { _oldCDef2expectedMinus = value; } }

		private DateTime? _executeDate;
        /// <summary>
        /// 实施日期
        /// </summary>
		public DateTime? ExecuteDate
		{ get { return _executeDate; } set { _executeDate = value; } }

		private Decimal? _qty1Old;
        /// <summary>
        /// 系统提供原法定数量
        /// </summary>
		public Decimal? Qty1Old
		{ get { return _qty1Old; } set { _qty1Old = value; } }

		private Decimal? _def2expectedOldR;
        /// <summary>
        /// 原直属海关理论税差
        /// </summary>
		public Decimal? Def2expectedOldR
		{ get { return _def2expectedOldR; } set { _def2expectedOldR = value; } }

		private Decimal? _qty1OldF;
        /// <summary>
        /// 强制输入原法定数量
        /// </summary>
		public Decimal? Qty1OldF
		{ get { return _qty1OldF; } set { _qty1OldF = value; } }

		private Decimal? _newCPriceLevelPlusR;
        /// <summary>
        /// 拟改成税号加入被调整商品项后的直属海关价格水平
        /// </summary>
		public Decimal? NewCPriceLevelPlusR
		{ get { return _newCPriceLevelPlusR; } set { _newCPriceLevelPlusR = value; } }

		private Decimal? _tradeTotalOldF;
        /// <summary>
        /// 强制输入原成交总价
        /// </summary>
		public Decimal? TradeTotalOldF
		{ get { return _tradeTotalOldF; } set { _tradeTotalOldF = value; } }

		private Int32? _versionN;
        /// <summary>
        /// 提交时的全国水平数据版本
        /// </summary>
		public Int32? VersionN
		{ get { return _versionN; } set { _versionN = value; } }

		private Decimal? _antiRateOld;
        /// <summary>
        /// 系统提供原实征从价反倾销税税率
        /// </summary>
		public Decimal? AntiRateOld
		{ get { return _antiRateOld; } set { _antiRateOld = value; } }

		private String _executorId;
        /// <summary>
        /// 实施修改人标识
        /// </summary>
		public String ExecutorId
		{ get { return _executorId; } set { _executorId = value; } }

		private Decimal? _taxRateOldF;
        /// <summary>
        /// 强制输入原实征从价增值税率
        /// </summary>
		public Decimal? TaxRateOldF
		{ get { return _taxRateOldF; } set { _taxRateOldF = value; } }

		private Decimal? _priceLevel2be;
        /// <summary>
        /// 拟改成的口岸价格水平
        /// </summary>
		public Decimal? PriceLevel2be
		{ get { return _priceLevel2be; } set { _priceLevel2be = value; } }

		private DateTime? _releaseDate;
        /// <summary>
        /// 放行日期时间
        /// </summary>
		public DateTime? ReleaseDate
		{ get { return _releaseDate; } set { _releaseDate = value; } }

		private Decimal? _taxRate2be;
        /// <summary>
        /// 拟改成的实征从价增值税率
        /// </summary>
		public Decimal? TaxRate2be
		{ get { return _taxRate2be; } set { _taxRate2be = value; } }

		private Decimal? _newCDef2expectedPlusR;
        /// <summary>
        /// 拟改成税号加入被调整商品项后的直属海关理论税差
        /// </summary>
		public Decimal? NewCDef2expectedPlusR
		{ get { return _newCDef2expectedPlusR; } set { _newCDef2expectedPlusR = value; } }

		private String _entryId;
        /// <summary>
        /// 报关单号
        /// </summary>
		public String EntryId
		{ get { return _entryId; } set { _entryId = value; } }

		private Decimal? _oldCPriceLevelMinus;
        /// <summary>
        /// 原税号剔除被调整商品项后的口岸价格水平
        /// </summary>
		public Decimal? OldCPriceLevelMinus
		{ get { return _oldCPriceLevelMinus; } set { _oldCPriceLevelMinus = value; } }

		private Decimal? _def2expected2beR;
        /// <summary>
        /// 拟改成的直属海关理论税差
        /// </summary>
		public Decimal? Def2expected2beR
		{ get { return _def2expected2beR; } set { _def2expected2beR = value; } }

		private String _proposalSn;
        /// <summary>
        /// 测算流水号
        /// </summary>
		public String ProposalSn
		{ get { return _proposalSn; } set { _proposalSn = value; } }

		private Decimal? _priceLevel2beR;
        /// <summary>
        /// 拟改成的直属海关价格水平
        /// </summary>
		public Decimal? PriceLevel2beR
		{ get { return _priceLevel2beR; } set { _priceLevel2beR = value; } }

		private String _gNo;
        /// <summary>
        /// 商品序号
        /// </summary>
		public String GNo
		{ get { return _gNo; } set { _gNo = value; } }

		private Decimal? _oldCPriceLevelMinusR;
        /// <summary>
        /// 原税号剔除被调整商品项后的直属海关价格水平
        /// </summary>
		public Decimal? OldCPriceLevelMinusR
		{ get { return _oldCPriceLevelMinusR; } set { _oldCPriceLevelMinusR = value; } }

		private Decimal? _dutyRateOldF;
        /// <summary>
        /// 强制输入原实征从价关税率
        /// </summary>
		public Decimal? DutyRateOldF
		{ get { return _dutyRateOldF; } set { _dutyRateOldF = value; } }

		private Decimal? _def2expectedOld;
        /// <summary>
        /// 原口岸理论税差
        /// </summary>
		public Decimal? Def2expectedOld
		{ get { return _def2expectedOld; } set { _def2expectedOld = value; } }

		private String _codeTs2be;
        /// <summary>
        /// 拟改成的商品编号
        /// </summary>
		public String CodeTs2be
		{ get { return _codeTs2be; } set { _codeTs2be = value; } }

		private String _reason4fail2modi;
        /// <summary>
        /// 未修改原因
        /// </summary>
		public String Reason4fail2modi
		{ get { return _reason4fail2modi; } set { _reason4fail2modi = value; } }

		private Decimal? _regRate2be;
        /// <summary>
        /// 拟改成的实征从价消费税率
        /// </summary>
		public Decimal? RegRate2be
		{ get { return _regRate2be; } set { _regRate2be = value; } }

		private Decimal? _qty12be;
        /// <summary>
        /// 拟改成的法定数量
        /// </summary>
		public Decimal? Qty12be
		{ get { return _qty12be; } set { _qty12be = value; } }

		private String _proposerId;
        /// <summary>
        /// 提交修改人标识
        /// </summary>
		public String ProposerId
		{ get { return _proposerId; } set { _proposerId = value; } }

		private Decimal? _oldCDef2expectedMinusR;
        /// <summary>
        /// 原税号剔除被调整商品项后的直属海关理论税差
        /// </summary>
		public Decimal? OldCDef2expectedMinusR
		{ get { return _oldCDef2expectedMinusR; } set { _oldCDef2expectedMinusR = value; } }

		private Decimal? _newCDef2expectedPlus;
        /// <summary>
        /// 拟改成税号加入被调整商品项后的口岸理论税差
        /// </summary>
		public Decimal? NewCDef2expectedPlus
		{ get { return _newCDef2expectedPlus; } set { _newCDef2expectedPlus = value; } }

		private String _codeTsOldF;
        /// <summary>
        /// 强制输入原商品编号
        /// </summary>
		public String CodeTsOldF
		{ get { return _codeTsOldF; } set { _codeTsOldF = value; } }

		private Decimal? _def2expected2be;
        /// <summary>
        /// 拟改成的口岸理论税差
        /// </summary>
		public Decimal? Def2expected2be
		{ get { return _def2expected2be; } set { _def2expected2be = value; } }

		private Decimal? _tradeTotal2be;
        /// <summary>
        /// 拟改成的成交总价
        /// </summary>
		public Decimal? TradeTotal2be
		{ get { return _tradeTotal2be; } set { _tradeTotal2be = value; } }

		private Decimal? _taxRateOld;
        /// <summary>
        /// 系统提供原实征从价增值税率
        /// </summary>
		public Decimal? TaxRateOld
		{ get { return _taxRateOld; } set { _taxRateOld = value; } }

		private String _codeTsOld;
        /// <summary>
        /// 系统提供原商品编号
        /// </summary>
		public String CodeTsOld
		{ get { return _codeTsOld; } set { _codeTsOld = value; } }

		private Decimal? _dutyRateOld;
        /// <summary>
        /// 系统提供原实征从价关税率
        /// </summary>
		public Decimal? DutyRateOld
		{ get { return _dutyRateOld; } set { _dutyRateOld = value; } }

		private Decimal? _dutyRate2be;
        /// <summary>
        /// 拟改成的实征从价关税率
        /// </summary>
		public Decimal? DutyRate2be
		{ get { return _dutyRate2be; } set { _dutyRate2be = value; } }

		private DateTime? _proposeDate;
        /// <summary>
        /// 提交日期
        /// </summary>
		public DateTime? ProposeDate
		{ get { return _proposeDate; } set { _proposeDate = value; } }

		private String _modiFlag;
        /// <summary>
        /// 修改种类标志，分别为修改报关单价p、数量q、税号c
        /// </summary>
		public String ModiFlag
		{ get { return _modiFlag; } set { _modiFlag = value; } }

		private Decimal? _priceLevelOld;
        /// <summary>
        /// 原口岸价格水平
        /// </summary>
		public Decimal? PriceLevelOld
		{ get { return _priceLevelOld; } set { _priceLevelOld = value; } }

		private Decimal? _antiRate2be;
        /// <summary>
        /// 拟改成的实征从价反倾销税税率
        /// </summary>
		public Decimal? AntiRate2be
		{ get { return _antiRate2be; } set { _antiRate2be = value; } }

		private Decimal? _regRateOldF;
        /// <summary>
        /// 强制输入原实征从价消费税率
        /// </summary>
		public Decimal? RegRateOldF
		{ get { return _regRateOldF; } set { _regRateOldF = value; } }

		private Decimal? _regRateOld;
        /// <summary>
        /// 系统提供原实征从价消费税率
        /// </summary>
		public Decimal? RegRateOld
		{ get { return _regRateOld; } set { _regRateOld = value; } }

		private Decimal? _antiRateOldF;
        /// <summary>
        /// 强制输入原实征从价反倾销税税率
        /// </summary>
		public Decimal? AntiRateOldF
		{ get { return _antiRateOldF; } set { _antiRateOldF = value; } }

		private String _abnormalityCode;
        /// <summary>
        /// 测算异常代码
        /// </summary>
		public String AbnormalityCode
		{ get { return _abnormalityCode; } set { _abnormalityCode = value; } }

		private Int32? _versionL;
        /// <summary>
        /// 提交时的本地水平数据版本
        /// </summary>
		public Int32? VersionL
		{ get { return _versionL; } set { _versionL = value; } }

		private Decimal? _priceLevelOldR;
        /// <summary>
        /// 原直属海关价格水平
        /// </summary>
		public Decimal? PriceLevelOldR
		{ get { return _priceLevelOldR; } set { _priceLevelOldR = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "ADJUSTMENT_PERFORM";
        /// <summary>
        /// 属性名称定义 系统提供原成交总价
        /// </summary>
public const string PropertyNameTradeTotalOld = "TradeTotalOld";
        /// <summary>
        /// 字段名称定义 系统提供原成交总价
        /// </summary>
public const string FieldNameTradeTotalOld = "TRADE_TOTAL_OLD";
        /// <summary>
        /// 属性名称定义 拟改成税号加入被调整商品项后的口岸价格水平
        /// </summary>
public const string PropertyNameNewCPriceLevelPlus = "NewCPriceLevelPlus";
        /// <summary>
        /// 字段名称定义 拟改成税号加入被调整商品项后的口岸价格水平
        /// </summary>
public const string FieldNameNewCPriceLevelPlus = "NEW_C_PRICE_LEVEL_PLUS";
        /// <summary>
        /// 属性名称定义 原税号剔除被调整商品项后的口岸理论税差
        /// </summary>
public const string PropertyNameOldCDef2expectedMinus = "OldCDef2expectedMinus";
        /// <summary>
        /// 字段名称定义 原税号剔除被调整商品项后的口岸理论税差
        /// </summary>
public const string FieldNameOldCDef2expectedMinus = "OLD_C_DEF_2EXPECTED_MINUS";
        /// <summary>
        /// 属性名称定义 实施日期
        /// </summary>
public const string PropertyNameExecuteDate = "ExecuteDate";
        /// <summary>
        /// 字段名称定义 实施日期
        /// </summary>
public const string FieldNameExecuteDate = "EXECUTE_DATE";
        /// <summary>
        /// 属性名称定义 系统提供原法定数量
        /// </summary>
public const string PropertyNameQty1Old = "Qty1Old";
        /// <summary>
        /// 字段名称定义 系统提供原法定数量
        /// </summary>
public const string FieldNameQty1Old = "QTY_1_OLD";
        /// <summary>
        /// 属性名称定义 原直属海关理论税差
        /// </summary>
public const string PropertyNameDef2expectedOldR = "Def2expectedOldR";
        /// <summary>
        /// 字段名称定义 原直属海关理论税差
        /// </summary>
public const string FieldNameDef2expectedOldR = "DEF_2EXPECTED_OLD_R";
        /// <summary>
        /// 属性名称定义 强制输入原法定数量
        /// </summary>
public const string PropertyNameQty1OldF = "Qty1OldF";
        /// <summary>
        /// 字段名称定义 强制输入原法定数量
        /// </summary>
public const string FieldNameQty1OldF = "QTY_1_OLD_F";
        /// <summary>
        /// 属性名称定义 拟改成税号加入被调整商品项后的直属海关价格水平
        /// </summary>
public const string PropertyNameNewCPriceLevelPlusR = "NewCPriceLevelPlusR";
        /// <summary>
        /// 字段名称定义 拟改成税号加入被调整商品项后的直属海关价格水平
        /// </summary>
public const string FieldNameNewCPriceLevelPlusR = "NEW_C_PRICE_LEVEL_PLUS_R";
        /// <summary>
        /// 属性名称定义 强制输入原成交总价
        /// </summary>
public const string PropertyNameTradeTotalOldF = "TradeTotalOldF";
        /// <summary>
        /// 字段名称定义 强制输入原成交总价
        /// </summary>
public const string FieldNameTradeTotalOldF = "TRADE_TOTAL_OLD_F";
        /// <summary>
        /// 属性名称定义 提交时的全国水平数据版本
        /// </summary>
public const string PropertyNameVersionN = "VersionN";
        /// <summary>
        /// 字段名称定义 提交时的全国水平数据版本
        /// </summary>
public const string FieldNameVersionN = "VERSION_N";
        /// <summary>
        /// 属性名称定义 系统提供原实征从价反倾销税税率
        /// </summary>
public const string PropertyNameAntiRateOld = "AntiRateOld";
        /// <summary>
        /// 字段名称定义 系统提供原实征从价反倾销税税率
        /// </summary>
public const string FieldNameAntiRateOld = "ANTI_RATE_OLD";
        /// <summary>
        /// 属性名称定义 实施修改人标识
        /// </summary>
public const string PropertyNameExecutorId = "ExecutorId";
        /// <summary>
        /// 字段名称定义 实施修改人标识
        /// </summary>
public const string FieldNameExecutorId = "EXECUTOR_ID";
        /// <summary>
        /// 属性名称定义 强制输入原实征从价增值税率
        /// </summary>
public const string PropertyNameTaxRateOldF = "TaxRateOldF";
        /// <summary>
        /// 字段名称定义 强制输入原实征从价增值税率
        /// </summary>
public const string FieldNameTaxRateOldF = "TAX_RATE_OLD_F";
        /// <summary>
        /// 属性名称定义 拟改成的口岸价格水平
        /// </summary>
public const string PropertyNamePriceLevel2be = "PriceLevel2be";
        /// <summary>
        /// 字段名称定义 拟改成的口岸价格水平
        /// </summary>
public const string FieldNamePriceLevel2be = "PRICE_LEVEL_2BE";
        /// <summary>
        /// 属性名称定义 放行日期时间
        /// </summary>
public const string PropertyNameReleaseDate = "ReleaseDate";
        /// <summary>
        /// 字段名称定义 放行日期时间
        /// </summary>
public const string FieldNameReleaseDate = "RELEASE_DATE";
        /// <summary>
        /// 属性名称定义 拟改成的实征从价增值税率
        /// </summary>
public const string PropertyNameTaxRate2be = "TaxRate2be";
        /// <summary>
        /// 字段名称定义 拟改成的实征从价增值税率
        /// </summary>
public const string FieldNameTaxRate2be = "TAX_RATE_2BE";
        /// <summary>
        /// 属性名称定义 拟改成税号加入被调整商品项后的直属海关理论税差
        /// </summary>
public const string PropertyNameNewCDef2expectedPlusR = "NewCDef2expectedPlusR";
        /// <summary>
        /// 字段名称定义 拟改成税号加入被调整商品项后的直属海关理论税差
        /// </summary>
public const string FieldNameNewCDef2expectedPlusR = "NEW_C_DEF_2EXPECTED_PLUS_R";
        /// <summary>
        /// 属性名称定义 报关单号
        /// </summary>
public const string PropertyNameEntryId = "EntryId";
        /// <summary>
        /// 字段名称定义 报关单号
        /// </summary>
public const string FieldNameEntryId = "ENTRY_ID";
        /// <summary>
        /// 属性名称定义 原税号剔除被调整商品项后的口岸价格水平
        /// </summary>
public const string PropertyNameOldCPriceLevelMinus = "OldCPriceLevelMinus";
        /// <summary>
        /// 字段名称定义 原税号剔除被调整商品项后的口岸价格水平
        /// </summary>
public const string FieldNameOldCPriceLevelMinus = "OLD_C_PRICE_LEVEL_MINUS";
        /// <summary>
        /// 属性名称定义 拟改成的直属海关理论税差
        /// </summary>
public const string PropertyNameDef2expected2beR = "Def2expected2beR";
        /// <summary>
        /// 字段名称定义 拟改成的直属海关理论税差
        /// </summary>
public const string FieldNameDef2expected2beR = "DEF_2EXPECTED_2BE_R";
        /// <summary>
        /// 属性名称定义 测算流水号
        /// </summary>
public const string PropertyNameProposalSn = "ProposalSn";
        /// <summary>
        /// 字段名称定义 测算流水号
        /// </summary>
public const string FieldNameProposalSn = "PROPOSAL_SN";
        /// <summary>
        /// 属性名称定义 拟改成的直属海关价格水平
        /// </summary>
public const string PropertyNamePriceLevel2beR = "PriceLevel2beR";
        /// <summary>
        /// 字段名称定义 拟改成的直属海关价格水平
        /// </summary>
public const string FieldNamePriceLevel2beR = "PRICE_LEVEL_2BE_R";
        /// <summary>
        /// 属性名称定义 商品序号
        /// </summary>
public const string PropertyNameGNo = "GNo";
        /// <summary>
        /// 字段名称定义 商品序号
        /// </summary>
public const string FieldNameGNo = "G_NO";
        /// <summary>
        /// 属性名称定义 原税号剔除被调整商品项后的直属海关价格水平
        /// </summary>
public const string PropertyNameOldCPriceLevelMinusR = "OldCPriceLevelMinusR";
        /// <summary>
        /// 字段名称定义 原税号剔除被调整商品项后的直属海关价格水平
        /// </summary>
public const string FieldNameOldCPriceLevelMinusR = "OLD_C_PRICE_LEVEL_MINUS_R";
        /// <summary>
        /// 属性名称定义 强制输入原实征从价关税率
        /// </summary>
public const string PropertyNameDutyRateOldF = "DutyRateOldF";
        /// <summary>
        /// 字段名称定义 强制输入原实征从价关税率
        /// </summary>
public const string FieldNameDutyRateOldF = "DUTY_RATE_OLD_F";
        /// <summary>
        /// 属性名称定义 原口岸理论税差
        /// </summary>
public const string PropertyNameDef2expectedOld = "Def2expectedOld";
        /// <summary>
        /// 字段名称定义 原口岸理论税差
        /// </summary>
public const string FieldNameDef2expectedOld = "DEF_2EXPECTED_OLD";
        /// <summary>
        /// 属性名称定义 拟改成的商品编号
        /// </summary>
public const string PropertyNameCodeTs2be = "CodeTs2be";
        /// <summary>
        /// 字段名称定义 拟改成的商品编号
        /// </summary>
public const string FieldNameCodeTs2be = "CODE_TS_2BE";
        /// <summary>
        /// 属性名称定义 未修改原因
        /// </summary>
public const string PropertyNameReason4fail2modi = "Reason4fail2modi";
        /// <summary>
        /// 字段名称定义 未修改原因
        /// </summary>
public const string FieldNameReason4fail2modi = "REASON4FAIL2MODI";
        /// <summary>
        /// 属性名称定义 拟改成的实征从价消费税率
        /// </summary>
public const string PropertyNameRegRate2be = "RegRate2be";
        /// <summary>
        /// 字段名称定义 拟改成的实征从价消费税率
        /// </summary>
public const string FieldNameRegRate2be = "REG_RATE_2BE";
        /// <summary>
        /// 属性名称定义 拟改成的法定数量
        /// </summary>
public const string PropertyNameQty12be = "Qty12be";
        /// <summary>
        /// 字段名称定义 拟改成的法定数量
        /// </summary>
public const string FieldNameQty12be = "QTY_1_2BE";
        /// <summary>
        /// 属性名称定义 提交修改人标识
        /// </summary>
public const string PropertyNameProposerId = "ProposerId";
        /// <summary>
        /// 字段名称定义 提交修改人标识
        /// </summary>
public const string FieldNameProposerId = "PROPOSER_ID";
        /// <summary>
        /// 属性名称定义 原税号剔除被调整商品项后的直属海关理论税差
        /// </summary>
public const string PropertyNameOldCDef2expectedMinusR = "OldCDef2expectedMinusR";
        /// <summary>
        /// 字段名称定义 原税号剔除被调整商品项后的直属海关理论税差
        /// </summary>
public const string FieldNameOldCDef2expectedMinusR = "OLD_C_DEF_2EXPECTED_MINUS_R";
        /// <summary>
        /// 属性名称定义 拟改成税号加入被调整商品项后的口岸理论税差
        /// </summary>
public const string PropertyNameNewCDef2expectedPlus = "NewCDef2expectedPlus";
        /// <summary>
        /// 字段名称定义 拟改成税号加入被调整商品项后的口岸理论税差
        /// </summary>
public const string FieldNameNewCDef2expectedPlus = "NEW_C_DEF_2EXPECTED_PLUS";
        /// <summary>
        /// 属性名称定义 强制输入原商品编号
        /// </summary>
public const string PropertyNameCodeTsOldF = "CodeTsOldF";
        /// <summary>
        /// 字段名称定义 强制输入原商品编号
        /// </summary>
public const string FieldNameCodeTsOldF = "CODE_TS_OLD_F";
        /// <summary>
        /// 属性名称定义 拟改成的口岸理论税差
        /// </summary>
public const string PropertyNameDef2expected2be = "Def2expected2be";
        /// <summary>
        /// 字段名称定义 拟改成的口岸理论税差
        /// </summary>
public const string FieldNameDef2expected2be = "DEF_2EXPECTED_2BE";
        /// <summary>
        /// 属性名称定义 拟改成的成交总价
        /// </summary>
public const string PropertyNameTradeTotal2be = "TradeTotal2be";
        /// <summary>
        /// 字段名称定义 拟改成的成交总价
        /// </summary>
public const string FieldNameTradeTotal2be = "TRADE_TOTAL_2BE";
        /// <summary>
        /// 属性名称定义 系统提供原实征从价增值税率
        /// </summary>
public const string PropertyNameTaxRateOld = "TaxRateOld";
        /// <summary>
        /// 字段名称定义 系统提供原实征从价增值税率
        /// </summary>
public const string FieldNameTaxRateOld = "TAX_RATE_OLD";
        /// <summary>
        /// 属性名称定义 系统提供原商品编号
        /// </summary>
public const string PropertyNameCodeTsOld = "CodeTsOld";
        /// <summary>
        /// 字段名称定义 系统提供原商品编号
        /// </summary>
public const string FieldNameCodeTsOld = "CODE_TS_OLD";
        /// <summary>
        /// 属性名称定义 系统提供原实征从价关税率
        /// </summary>
public const string PropertyNameDutyRateOld = "DutyRateOld";
        /// <summary>
        /// 字段名称定义 系统提供原实征从价关税率
        /// </summary>
public const string FieldNameDutyRateOld = "DUTY_RATE_OLD";
        /// <summary>
        /// 属性名称定义 拟改成的实征从价关税率
        /// </summary>
public const string PropertyNameDutyRate2be = "DutyRate2be";
        /// <summary>
        /// 字段名称定义 拟改成的实征从价关税率
        /// </summary>
public const string FieldNameDutyRate2be = "DUTY_RATE_2BE";
        /// <summary>
        /// 属性名称定义 提交日期
        /// </summary>
public const string PropertyNameProposeDate = "ProposeDate";
        /// <summary>
        /// 字段名称定义 提交日期
        /// </summary>
public const string FieldNameProposeDate = "PROPOSE_DATE";
        /// <summary>
        /// 属性名称定义 修改种类标志，分别为修改报关单价p、数量q、税号c
        /// </summary>
public const string PropertyNameModiFlag = "ModiFlag";
        /// <summary>
        /// 字段名称定义 修改种类标志，分别为修改报关单价p、数量q、税号c
        /// </summary>
public const string FieldNameModiFlag = "MODI_FLAG";
        /// <summary>
        /// 属性名称定义 原口岸价格水平
        /// </summary>
public const string PropertyNamePriceLevelOld = "PriceLevelOld";
        /// <summary>
        /// 字段名称定义 原口岸价格水平
        /// </summary>
public const string FieldNamePriceLevelOld = "PRICE_LEVEL_OLD";
        /// <summary>
        /// 属性名称定义 拟改成的实征从价反倾销税税率
        /// </summary>
public const string PropertyNameAntiRate2be = "AntiRate2be";
        /// <summary>
        /// 字段名称定义 拟改成的实征从价反倾销税税率
        /// </summary>
public const string FieldNameAntiRate2be = "ANTI_RATE_2BE";
        /// <summary>
        /// 属性名称定义 强制输入原实征从价消费税率
        /// </summary>
public const string PropertyNameRegRateOldF = "RegRateOldF";
        /// <summary>
        /// 字段名称定义 强制输入原实征从价消费税率
        /// </summary>
public const string FieldNameRegRateOldF = "REG_RATE_OLD_F";
        /// <summary>
        /// 属性名称定义 系统提供原实征从价消费税率
        /// </summary>
public const string PropertyNameRegRateOld = "RegRateOld";
        /// <summary>
        /// 字段名称定义 系统提供原实征从价消费税率
        /// </summary>
public const string FieldNameRegRateOld = "REG_RATE_OLD";
        /// <summary>
        /// 属性名称定义 强制输入原实征从价反倾销税税率
        /// </summary>
public const string PropertyNameAntiRateOldF = "AntiRateOldF";
        /// <summary>
        /// 字段名称定义 强制输入原实征从价反倾销税税率
        /// </summary>
public const string FieldNameAntiRateOldF = "ANTI_RATE_OLD_F";
        /// <summary>
        /// 属性名称定义 测算异常代码
        /// </summary>
public const string PropertyNameAbnormalityCode = "AbnormalityCode";
        /// <summary>
        /// 字段名称定义 测算异常代码
        /// </summary>
public const string FieldNameAbnormalityCode = "ABNORMALITY_CODE";
        /// <summary>
        /// 属性名称定义 提交时的本地水平数据版本
        /// </summary>
public const string PropertyNameVersionL = "VersionL";
        /// <summary>
        /// 字段名称定义 提交时的本地水平数据版本
        /// </summary>
public const string FieldNameVersionL = "VERSION_L";
        /// <summary>
        /// 属性名称定义 原直属海关价格水平
        /// </summary>
public const string PropertyNamePriceLevelOldR = "PriceLevelOldR";
        /// <summary>
        /// 字段名称定义 原直属海关价格水平
        /// </summary>
public const string FieldNamePriceLevelOldR = "PRICE_LEVEL_OLD_R";

        }
#endregion
	}
}
