// Auto generated by MappingTools at 2009-11-06 09:48:33

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Entity
{
        /// <summary>
        /// 归口单位名称
        /// </summary>
	public partial class T_AuthorityName
	{
		private String _competentAuthorityId;
        /// <summary>
        /// 归口单位代码
        /// </summary>
		public String CompetentAuthorityId
		{ get { return _competentAuthorityId; } set { _competentAuthorityId = value; } }

		private String _authorityAbbr;
        /// <summary>
        /// 归口单位简称
        /// </summary>
		public String AuthorityAbbr
		{ get { return _authorityAbbr; } set { _authorityAbbr = value; } }

		private String _competencePartition;
        /// <summary>
        /// 归口办法
        /// </summary>
		public String CompetencePartition
		{ get { return _competencePartition; } set { _competencePartition = value; } }

		private String _authorityName;
        /// <summary>
        /// 归口单位全称
        /// </summary>
		public String AuthorityName
		{ get { return _authorityName; } set { _authorityName = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "AUTHORITY_NAME";
        /// <summary>
        /// 属性名称定义 归口单位代码
        /// </summary>
public const string PropertyNameCompetentAuthorityId = "CompetentAuthorityId";
        /// <summary>
        /// 字段名称定义 归口单位代码
        /// </summary>
public const string FieldNameCompetentAuthorityId = "COMPETENT_AUTHORITY_ID";
        /// <summary>
        /// 属性名称定义 归口单位简称
        /// </summary>
public const string PropertyNameAuthorityAbbr = "AuthorityAbbr";
        /// <summary>
        /// 字段名称定义 归口单位简称
        /// </summary>
public const string FieldNameAuthorityAbbr = "AUTHORITY_ABBR";
        /// <summary>
        /// 属性名称定义 归口办法
        /// </summary>
public const string PropertyNameCompetencePartition = "CompetencePartition";
        /// <summary>
        /// 字段名称定义 归口办法
        /// </summary>
public const string FieldNameCompetencePartition = "COMPETENCE_PARTITION";
        /// <summary>
        /// 属性名称定义 归口单位全称
        /// </summary>
public const string PropertyNameAuthorityName = "AuthorityName";
        /// <summary>
        /// 字段名称定义 归口单位全称
        /// </summary>
public const string FieldNameAuthorityName = "AUTHORITY_NAME";

        }
#endregion
	}
}
