// Auto generated by MappingTools at 2009-11-06 09:48:34

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_Customs
	{
		private String _abbrCust;
        /// <summary>
        /// 
        /// </summary>
		public String AbbrCust
		{ get { return _abbrCust; } set { _abbrCust = value; } }

		private String _customsCode;
        /// <summary>
        /// 
        /// </summary>
		public String CustomsCode
		{ get { return _customsCode; } set { _customsCode = value; } }

		private String _customsName;
        /// <summary>
        /// 
        /// </summary>
		public String CustomsName
		{ get { return _customsName; } set { _customsName = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "CUSTOMS";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameAbbrCust = "AbbrCust";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameAbbrCust = "ABBR_CUST";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomsCode = "CustomsCode";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomsCode = "CUSTOMS_CODE";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCustomsName = "CustomsName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCustomsName = "CUSTOMS_NAME";

        }
#endregion
	}
}
