// Auto generated by MappingTools at 2009-11-06 09:48:34

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Entity
{
        /// <summary>
        /// 口岸隶属关系
        /// </summary>
	public partial class T_Jurisdiction
	{
		private String _competentAuthorityId;
        /// <summary>
        /// 归口单位代码：当归口办法为1时，即相应的隶属海关代码。
        /// </summary>
		public String CompetentAuthorityId
		{ get { return _competentAuthorityId; } set { _competentAuthorityId = value; } }

		private String _portId;
        /// <summary>
        /// 口岸代码
        /// </summary>
		public String PortId
		{ get { return _portId; } set { _portId = value; } }

		private String _competencePartition;
        /// <summary>
        /// 归口办法：1-目前上海海关的海关估价管理业务的基本归口。
        /// </summary>
		public String CompetencePartition
		{ get { return _competencePartition; } set { _competencePartition = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "JURISDICTION";
        /// <summary>
        /// 属性名称定义 归口单位代码
        /// </summary>
public const string PropertyNameCompetentAuthorityId = "CompetentAuthorityId";
        /// <summary>
        /// 字段名称定义 归口单位代码
        /// </summary>
public const string FieldNameCompetentAuthorityId = "COMPETENT_AUTHORITY_ID";
        /// <summary>
        /// 属性名称定义 口岸代码
        /// </summary>
public const string PropertyNamePortId = "PortId";
        /// <summary>
        /// 字段名称定义 口岸代码
        /// </summary>
public const string FieldNamePortId = "PORT_ID";
        /// <summary>
        /// 属性名称定义 归口办法
        /// </summary>
public const string PropertyNameCompetencePartition = "CompetencePartition";
        /// <summary>
        /// 字段名称定义 归口办法
        /// </summary>
public const string FieldNameCompetencePartition = "COMPETENCE_PARTITION";

        }
#endregion
	}
}
