// Auto generated by MappingTools at 2009-11-06 09:48:40

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Entity
{
        /// <summary>
        /// 全国水平年度数据
        /// </summary>
	public partial class T_NationPerformY
	{
		private Decimal? _qty1;
        /// <summary>
        /// 第一（法定）数量
        /// </summary>
		public Decimal? Qty1
		{ get { return _qty1; } set { _qty1 = value; } }

		private Int64? _dutyValue;
        /// <summary>
        /// 关税完税价
        /// </summary>
		public Int64? DutyValue
		{ get { return _dutyValue; } set { _dutyValue = value; } }

		private Decimal? _realTotal;
        /// <summary>
        /// 实征税款
        /// </summary>
		public Decimal? RealTotal
		{ get { return _realTotal; } set { _realTotal = value; } }

		private String _trafMode;
        /// <summary>
        /// 运输方式：空格-不分运输方式；5-空运。
        /// </summary>
		public String TrafMode
		{ get { return _trafMode; } set { _trafMode = value; } }

		private String _periodId;
        /// <summary>
        /// 周期标识（PIC YYYY）
        /// </summary>
		public String PeriodId
		{ get { return _periodId; } set { _periodId = value; } }

		private Int32? _rank;
        /// <summary>
        /// 税收排名
        /// </summary>
		public Int32? Rank
		{ get { return _rank; } set { _rank = value; } }

		private String _tradeMode;
        /// <summary>
        /// 监管方式
        /// </summary>
		public String TradeMode
		{ get { return _tradeMode; } set { _tradeMode = value; } }

		private String _codeTs;
        /// <summary>
        /// 商品编号
        /// </summary>
		public String CodeTs
		{ get { return _codeTs; } set { _codeTs = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "NATION_PERFORM_Y";
        /// <summary>
        /// 属性名称定义 第一（法定）数量
        /// </summary>
public const string PropertyNameQty1 = "Qty1";
        /// <summary>
        /// 字段名称定义 第一（法定）数量
        /// </summary>
public const string FieldNameQty1 = "QTY_1";
        /// <summary>
        /// 属性名称定义 关税完税价
        /// </summary>
public const string PropertyNameDutyValue = "DutyValue";
        /// <summary>
        /// 字段名称定义 关税完税价
        /// </summary>
public const string FieldNameDutyValue = "DUTY_VALUE";
        /// <summary>
        /// 属性名称定义 实征税款
        /// </summary>
public const string PropertyNameRealTotal = "RealTotal";
        /// <summary>
        /// 字段名称定义 实征税款
        /// </summary>
public const string FieldNameRealTotal = "REAL_TOTAL";
        /// <summary>
        /// 属性名称定义 运输方式
        /// </summary>
public const string PropertyNameTrafMode = "TrafMode";
        /// <summary>
        /// 字段名称定义 运输方式
        /// </summary>
public const string FieldNameTrafMode = "TRAF_MODE";
        /// <summary>
        /// 属性名称定义 周期标识（PIC YYYY）
        /// </summary>
public const string PropertyNamePeriodId = "PeriodId";
        /// <summary>
        /// 字段名称定义 周期标识（PIC YYYY）
        /// </summary>
public const string FieldNamePeriodId = "PERIOD_ID";
        /// <summary>
        /// 属性名称定义 税收排名
        /// </summary>
public const string PropertyNameRank = "Rank";
        /// <summary>
        /// 字段名称定义 税收排名
        /// </summary>
public const string FieldNameRank = "RANK";
        /// <summary>
        /// 属性名称定义 监管方式
        /// </summary>
public const string PropertyNameTradeMode = "TradeMode";
        /// <summary>
        /// 字段名称定义 监管方式
        /// </summary>
public const string FieldNameTradeMode = "TRADE_MODE";
        /// <summary>
        /// 属性名称定义 商品编号
        /// </summary>
public const string PropertyNameCodeTs = "CodeTs";
        /// <summary>
        /// 字段名称定义 商品编号
        /// </summary>
public const string FieldNameCodeTs = "CODE_TS";

        }
#endregion
	}
}
