// Auto generated by MappingTools at 2009-11-06 09:48:42

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Entity
{
        /// <summary>
        /// 
        /// </summary>
	public partial class T_PlanTable
	{
		private Int32? _objectInstance;
        /// <summary>
        /// 
        /// </summary>
		public Int32? ObjectInstance
		{ get { return _objectInstance; } set { _objectInstance = value; } }

		private String _partitionStart;
        /// <summary>
        /// 
        /// </summary>
		public String PartitionStart
		{ get { return _partitionStart; } set { _partitionStart = value; } }

		private String _distribution;
        /// <summary>
        /// 
        /// </summary>
		public String Distribution
		{ get { return _distribution; } set { _distribution = value; } }

		private Int32? _ioCost;
        /// <summary>
        /// 
        /// </summary>
		public Int32? IoCost
		{ get { return _ioCost; } set { _ioCost = value; } }

		private Int32? _parentId;
        /// <summary>
        /// 
        /// </summary>
		public Int32? ParentId
		{ get { return _parentId; } set { _parentId = value; } }

		private Int32? _partitionId;
        /// <summary>
        /// 
        /// </summary>
		public Int32? PartitionId
		{ get { return _partitionId; } set { _partitionId = value; } }

		private Int32? _cardinality;
        /// <summary>
        /// 
        /// </summary>
		public Int32? Cardinality
		{ get { return _cardinality; } set { _cardinality = value; } }

		private Int32? _bytes;
        /// <summary>
        /// 
        /// </summary>
		public Int32? Bytes
		{ get { return _bytes; } set { _bytes = value; } }

		private String _options;
        /// <summary>
        /// 
        /// </summary>
		public String Options
		{ get { return _options; } set { _options = value; } }

		private DateTime? _timestamp;
        /// <summary>
        /// 
        /// </summary>
		public DateTime? Timestamp
		{ get { return _timestamp; } set { _timestamp = value; } }

		private String _partitionStop;
        /// <summary>
        /// 
        /// </summary>
		public String PartitionStop
		{ get { return _partitionStop; } set { _partitionStop = value; } }

		private Int32? _searchColumns;
        /// <summary>
        /// 
        /// </summary>
		public Int32? SearchColumns
		{ get { return _searchColumns; } set { _searchColumns = value; } }

		private String _remarks;
        /// <summary>
        /// 
        /// </summary>
		public String Remarks
		{ get { return _remarks; } set { _remarks = value; } }

		private String _objectName;
        /// <summary>
        /// 
        /// </summary>
		public String ObjectName
		{ get { return _objectName; } set { _objectName = value; } }

		private String _objectNode;
        /// <summary>
        /// 
        /// </summary>
		public String ObjectNode
		{ get { return _objectNode; } set { _objectNode = value; } }

		private Int32? _tempSpace;
        /// <summary>
        /// 
        /// </summary>
		public Int32? TempSpace
		{ get { return _tempSpace; } set { _tempSpace = value; } }

		private Int32? _position;
        /// <summary>
        /// 
        /// </summary>
		public Int32? Position
		{ get { return _position; } set { _position = value; } }

		private String _other;
        /// <summary>
        /// 
        /// </summary>
		public String Other
		{ get { return _other; } set { _other = value; } }

		private String _objectType;
        /// <summary>
        /// 
        /// </summary>
		public String ObjectType
		{ get { return _objectType; } set { _objectType = value; } }

		private String _statementId;
        /// <summary>
        /// 
        /// </summary>
		public String StatementId
		{ get { return _statementId; } set { _statementId = value; } }

		private String _optimizer;
        /// <summary>
        /// 
        /// </summary>
		public String Optimizer
		{ get { return _optimizer; } set { _optimizer = value; } }

		private String _otherTag;
        /// <summary>
        /// 
        /// </summary>
		public String OtherTag
		{ get { return _otherTag; } set { _otherTag = value; } }

		private String _objectOwner;
        /// <summary>
        /// 
        /// </summary>
		public String ObjectOwner
		{ get { return _objectOwner; } set { _objectOwner = value; } }

		private String _operation;
        /// <summary>
        /// 
        /// </summary>
		public String Operation
		{ get { return _operation; } set { _operation = value; } }

		private Int32? _cost;
        /// <summary>
        /// 
        /// </summary>
		public Int32? Cost
		{ get { return _cost; } set { _cost = value; } }

		private Int32? _id;
        /// <summary>
        /// 
        /// </summary>
		public Int32? Id
		{ get { return _id; } set { _id = value; } }

		private Int32? _cpuCost;
        /// <summary>
        /// 
        /// </summary>
		public Int32? CpuCost
		{ get { return _cpuCost; } set { _cpuCost = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "PLAN_TABLE";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameObjectInstance = "ObjectInstance";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameObjectInstance = "OBJECT_INSTANCE";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePartitionStart = "PartitionStart";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePartitionStart = "PARTITION_START";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameDistribution = "Distribution";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameDistribution = "DISTRIBUTION";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameIoCost = "IoCost";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameIoCost = "IO_COST";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameParentId = "ParentId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameParentId = "PARENT_ID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePartitionId = "PartitionId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePartitionId = "PARTITION_ID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCardinality = "Cardinality";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCardinality = "CARDINALITY";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameBytes = "Bytes";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameBytes = "BYTES";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOptions = "Options";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOptions = "OPTIONS";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameTimestamp = "Timestamp";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameTimestamp = "TIMESTAMP";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePartitionStop = "PartitionStop";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePartitionStop = "PARTITION_STOP";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameSearchColumns = "SearchColumns";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameSearchColumns = "SEARCH_COLUMNS";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameRemarks = "Remarks";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameRemarks = "REMARKS";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameObjectName = "ObjectName";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameObjectName = "OBJECT_NAME";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameObjectNode = "ObjectNode";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameObjectNode = "OBJECT_NODE";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameTempSpace = "TempSpace";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameTempSpace = "TEMP_SPACE";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNamePosition = "Position";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNamePosition = "POSITION";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOther = "Other";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOther = "OTHER";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameObjectType = "ObjectType";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameObjectType = "OBJECT_TYPE";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameStatementId = "StatementId";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameStatementId = "STATEMENT_ID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOptimizer = "Optimizer";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOptimizer = "OPTIMIZER";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOtherTag = "OtherTag";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOtherTag = "OTHER_TAG";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameObjectOwner = "ObjectOwner";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameObjectOwner = "OBJECT_OWNER";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameOperation = "Operation";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameOperation = "OPERATION";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCost = "Cost";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCost = "COST";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameId = "Id";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameId = "ID";
        /// <summary>
        /// 属性名称定义 
        /// </summary>
public const string PropertyNameCpuCost = "CpuCost";
        /// <summary>
        /// 字段名称定义 
        /// </summary>
public const string FieldNameCpuCost = "CPU_COST";

        }
#endregion
	}
}
