// Auto generated by MappingTools at 2009-11-06 09:48:44

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Entity
{
        /// <summary>
        /// 用户授权
        /// </summary>
	public partial class T_UserAuth
	{
		private String _portId;
        /// <summary>
        /// 口岸代码
        /// </summary>
		public String PortId
		{ get { return _portId; } set { _portId = value; } }

		private String _opId;
        /// <summary>
        /// 用户标识
        /// </summary>
		public String OpId
		{ get { return _opId; } set { _opId = value; } }

		private String _userName;
        /// <summary>
        /// 用户名称
        /// </summary>
		public String UserName
		{ get { return _userName; } set { _userName = value; } }

		private String _active;
        /// <summary>
        /// 帐号激活否：Y-激活，N-否。
        /// </summary>
		public String Active
		{ get { return _active; } set { _active = value; } }

		private String _rank;
        /// <summary>
        /// 级别：A-主管部门；B-现场联络员；C-普通用户。
        /// </summary>
		public String Rank
		{ get { return _rank; } set { _rank = value; } }

		private String _roles;
        /// <summary>
        /// 角色代码列表
        /// </summary>
		public String Roles
		{ get { return _roles; } set { _roles = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "USER_AUTH";
        /// <summary>
        /// 属性名称定义 口岸代码
        /// </summary>
public const string PropertyNamePortId = "PortId";
        /// <summary>
        /// 字段名称定义 口岸代码
        /// </summary>
public const string FieldNamePortId = "PORT_ID";
        /// <summary>
        /// 属性名称定义 用户标识
        /// </summary>
public const string PropertyNameOpId = "OpId";
        /// <summary>
        /// 字段名称定义 用户标识
        /// </summary>
public const string FieldNameOpId = "OP_ID";
        /// <summary>
        /// 属性名称定义 用户名称
        /// </summary>
public const string PropertyNameUserName = "UserName";
        /// <summary>
        /// 字段名称定义 用户名称
        /// </summary>
public const string FieldNameUserName = "USER_NAME";
        /// <summary>
        /// 属性名称定义 帐号激活否
        /// </summary>
public const string PropertyNameActive = "Active";
        /// <summary>
        /// 字段名称定义 帐号激活否
        /// </summary>
public const string FieldNameActive = "ACTIVE";
        /// <summary>
        /// 属性名称定义 级别
        /// </summary>
public const string PropertyNameRank = "Rank";
        /// <summary>
        /// 字段名称定义 级别
        /// </summary>
public const string FieldNameRank = "RANK";
        /// <summary>
        /// 属性名称定义 角色代码列表
        /// </summary>
public const string PropertyNameRoles = "Roles";
        /// <summary>
        /// 字段名称定义 角色代码列表
        /// </summary>
public const string FieldNameRoles = "ROLES";

        }
#endregion
	}
}
