// Auto generated by MappingTools at 2009-11-06 09:48:45

using System;
using System.Collections.Generic;
using System.Text;

namespace PLM.Biz.Entity
{
        /// <summary>
        /// 整合数据版本控制
        /// </summary>
	public partial class T_VersionControl
	{
		private String _area;
        /// <summary>
        /// 地区范围：N-全国；L-本地。
        /// </summary>
		public String Area
		{ get { return _area; } set { _area = value; } }

		private Int32? _version;
        /// <summary>
        /// 版本：0-周期未满；非0的1位数字-周期满后的月数。
        /// </summary>
		public Int32? Version
		{ get { return _version; } set { _version = value; } }

		private String _periodLen;
        /// <summary>
        /// 周期长度：M-月度；Q-季度；Y-年度。
        /// </summary>
		public String PeriodLen
		{ get { return _periodLen; } set { _periodLen = value; } }

		private String _trafMode;
        /// <summary>
        /// 运输方式：全国：空格-不分运输方式；5-空运。 本地：空格。
        /// </summary>
		public String TrafMode
		{ get { return _trafMode; } set { _trafMode = value; } }

		private String _periodId;
        /// <summary>
        /// 周期标识（PIC随PERIOD_LEN：M-YYYYMM；Q-YYYYQ；Y-YYYY。）
        /// </summary>
		public String PeriodId
		{ get { return _periodId; } set { _periodId = value; } }

		private DateTime? _updateDate;
        /// <summary>
        /// 更新时间
        /// </summary>
		public DateTime? UpdateDate
		{ get { return _updateDate; } set { _updateDate = value; } }

#region 名称常量定义
        /// <summary>
        /// 名称常量定义
        /// </summary>
public static class NameDefine
        {
        /// <summary>
        /// 默认表名
        /// </summary>
public const string DefaultTableName = "VERSION_CONTROL";
        /// <summary>
        /// 属性名称定义 地区范围
        /// </summary>
public const string PropertyNameArea = "Area";
        /// <summary>
        /// 字段名称定义 地区范围
        /// </summary>
public const string FieldNameArea = "AREA";
        /// <summary>
        /// 属性名称定义 版本
        /// </summary>
public const string PropertyNameVersion = "Version";
        /// <summary>
        /// 字段名称定义 版本
        /// </summary>
public const string FieldNameVersion = "VERSION";
        /// <summary>
        /// 属性名称定义 周期长度
        /// </summary>
public const string PropertyNamePeriodLen = "PeriodLen";
        /// <summary>
        /// 字段名称定义 周期长度
        /// </summary>
public const string FieldNamePeriodLen = "PERIOD_LEN";
        /// <summary>
        /// 属性名称定义 运输方式
        /// </summary>
public const string PropertyNameTrafMode = "TrafMode";
        /// <summary>
        /// 字段名称定义 运输方式
        /// </summary>
public const string FieldNameTrafMode = "TRAF_MODE";
        /// <summary>
        /// 属性名称定义 周期标识（PIC随PERIOD_LEN
        /// </summary>
public const string PropertyNamePeriodId = "PeriodId";
        /// <summary>
        /// 字段名称定义 周期标识（PIC随PERIOD_LEN
        /// </summary>
public const string FieldNamePeriodId = "PERIOD_ID";
        /// <summary>
        /// 属性名称定义 更新时间
        /// </summary>
public const string PropertyNameUpdateDate = "UpdateDate";
        /// <summary>
        /// 字段名称定义 更新时间
        /// </summary>
public const string FieldNameUpdateDate = "UPDATE_DATE";

        }
#endregion
	}
}
