/******************************************************
* author :  chenjianwu
* email  :  chenjianwu@sh.intra.customs.gov.cn
* function: 
* Auto generated by MappingTools at 2019-05-22 16:18:02
******************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace ExportDrawbackManagement.Biz.Interface
{
        /// <summary>
        /// 表
        /// users
        /// 的查询参数类	
        /// 
        /// 参数如果是数组，那么一定是array[3]，其中array[0],array[2]分别可为空，表示最小最大值，array[1]表示等于查询。
        /// 范围查询参数必须是数值型或者日期型，枚举请手动修改参数类型或代码生成中设定。
        /// 例如，需要查询一个值=2的条件，para可以设定为array[0]=array[2]=null,array[1]=2。
        /// 需要查询大于0小于50，设定为array[0]=0,array[2]=50,array[1]=null
        /// 如果同时指定，那么表示or关系，等于array[1]，或介于array[0]-array[2]之间。
        /// 三个参数可以都不填写，或只填写1个，或2个。
        /// </summary>
	[Serializable]
	public partial class Q_Users : BaseQueryPara
	{
		private String _name;
        /// <summary>
        /// 
        /// </summary>
		public String Name
		{ get { return _name; } set { _name = value; } }

		private String _rank;
        /// <summary>
        /// 
        /// </summary>
		public String Rank
		{ get { return _rank; } set { _rank = value; } }

		private String _derpartment;
        /// <summary>
        /// 
        /// </summary>
		public String Derpartment
		{ get { return _derpartment; } set { _derpartment = value; } }

		private String _personId;
        /// <summary>
        /// 
        /// </summary>
		public String PersonId
		{ get { return _personId; } set { _personId = value; } }

		private String _roles;
        /// <summary>
        /// 
        /// </summary>
		public String Roles
		{ get { return _roles; } set { _roles = value; } }

		private String _password;
        /// <summary>
        /// 
        /// </summary>
		public String Password
		{ get { return _password; } set { _password = value; } }

		private String _username;
        /// <summary>
        /// 
        /// </summary>
		public String Username
		{ get { return _username; } set { _username = value; } }

	}
}
